using System.Collections.Generic;

namespace SMSModForge.Model;

/// <summary>
/// Catalog of vanilla bust GameObjects under <c>2_Bust_Manager</c> in
/// <c>CoreGameScene</c> in Starmaker Story 1.8E. Used by the Characters tab
/// so a character can borrow an existing in-game bust instead of the pack
/// shipping art of its own.
/// <para/>
/// The pack plugin treats vanilla bust references identically to pack
/// bust references — both are GameObject-name lookups under
/// <c>2_Bust_Manager</c>. The vanilla list just spares the author from
/// remembering the exact name.
/// <para/>
/// Derived from <c>a decompiled scene-hierarchy dump of the target game</c>
/// (lines 30323–45446).
/// <para/>
/// NOT every bust in that dump is listed here, and refreshing this list is
/// therefore not a matter of re-running the extraction. A number of busts
/// sit in the scene without any content that shows them — unreleased work,
/// which this tool has no business advertising. They are excluded
/// deliberately and are not named anywhere in this repository.
/// <para/>
/// To refresh against a new game version: run the bust audit in the
/// SMSDiagDebug plugin (F9 scans what references each bust, F11 exports the
/// art of the ones nothing references), review the shortlist with the game
/// authors, and add only what is confirmed shipped. Pasting the raw
/// extraction back in would undo this.
/// </summary>
public static class VanillaBusts
{
    public sealed record VanillaBust(string GoName, string Character);

    /// <summary>
    /// Every direct child of <c>2_Bust_Manager</c>. The <see cref="Character"/>
    /// field is a best-effort grouping derived from the GO name (the part
    /// before the first underscore or `Bust`-suffix) — used by the editor
    /// to render an "Anna ▸" / "Charlotte ▸" style grouped picker if we
    /// ever upgrade the UI. The grouping isn't authoritative; some names
    /// don't fit a clean prefix and fall back to themselves.
    /// </summary>
    public static readonly IReadOnlyList<VanillaBust> All = new VanillaBust[]
    {
        new("Anna_Bust",                                  "Anna"),
        new("Anna_Gym",                                   "Anna"),
        new("Anna_GreyHoodie",                            "Anna"),
        new("AnnaBedroom",                                "Anna"),
        new("AnnaWedding",                                "Anna"),
        new("Anna_Wine",                                  "Anna"),
        new("Anna_YellowSexy",                            "Anna"),
        new("Anna_Towel",                                 "Anna"),
        new("Anna_Nude",                                  "Anna"),
        new("Anna_BathrobeClosed",                        "Anna"),
        new("Anna_White_Lingerie",                        "Anna"),
        new("Anna_Black_Lingerie",                        "Anna"),
        new("Anna_Swimwear",                              "Anna"),
        new("Anna_Red_Pullover",                          "Anna"),
        new("Anna_GoldenBikini",                          "Anna"),
        new("Anna_CoolOutfit",                            "Anna"),
        new("Anna_RedTanktopo",                           "Anna"),
        new("Anna_RedOfficesuit",                         "Anna"),
        new("Anna_Maid",                                  "Anna"),
        new("Anna_Bimb",                                  "Anna"),
        new("Anna_Elf",                                   "Anna"),
        new("Anna_Hiking",                                "Anna"),
        new("Anna_LoveRoute",                             "Anna"),
        new("Anna_SlutRoute",                             "Anna"),
        new("Anna_Gaming",                                "Anna"),
        new("Anna_Teacher",                               "Anna"),
        new("Anna_Bunny",                                 "Anna"),
        new("Anna_SexWorker",                             "Anna"),
        new("Anna_Garden",                                "Anna"),
        new("Anna_China",                                 "Anna"),
        new("Anna_Trenchcoat",                            "Anna"),
        new("Anna_NudeCovering",                          "Anna"),
        new("Anna_Christmaswrapping",                     "Anna"),
        new("Anna_GreenPullover",                         "Anna"),
        new("Anna_WinterSlutty",                          "Anna"),
        new("Anna_TropicalDress",                         "Anna"),
        new("Anna_WhiteSwimsuitTropical",                 "Anna"),
        new("Anna_WinterOutfit",                          "Anna"),
        new("Anna_GoddessBikini",                         "Anna"),
        new("Anna_SilverDressDeluxe",                     "Anna"),
        new("Anna_YogaOutfit",                            "Anna"),
        new("Anna_ChainmailBikini",                       "Anna"),
        new("Anna_WitchDress",                            "Anna"),
        new("Anna_SuperheroOutfit",                       "Anna"),
        new("AnnaSunDressBust",                           "Anna"),
        new("AnnaDefaultIceCreamBust",                    "Anna"),
        new("Anna_ChristmasEventBust",                    "Anna"),
        new("Anna_ChristmasLingerieBust",                 "Anna"),
        new("Anna_PlayerBirthdayLingerie_Bust",           "Anna"),
        new("Anna_Newyearslingerie_Bust",                 "Anna"),
        new("Anna_NewyearsDress_Bust",                    "Anna"),
        new("Anna_CowBust",                               "Anna"),
        new("Anna_DemonBust",                             "Anna"),
        new("Anna_StudioElfBust",                         "Anna"),
        new("Anna_StudioCowBust",                         "Anna"),
        new("Anna_BlackBoxersBust",                       "Anna"),
        new("Anna_MegaBoobsBust",                         "Anna"),
        new("Anna_FutaBust",                              "Anna"),
        new("Anna_SlutRouteFishnetBust",                  "Anna"),
        new("Anna_LoveRouteRedSwimsuitBust",              "Anna"),
        new("AnnaBust_TightBust_Purpledress",             "Anna"),
        new("AnnaBust_TightBust_Gym",                     "Anna"),
        new("AnnaBust_TightBust_CyanTop",                 "Anna"),
        new("AnnaBust_OilUp_BlackBikini",                 "Anna"),
        new("Nikki_Bust_Default",                         "Nikki"),
        new("Nikki_Bust_Topless",                         "Nikki"),
        new("Android_normaloutfit",                       "Android"),
        new("CharlotteBust",                              "Charlotte"),
        new("Charlotte_Nude",                             "Charlotte"),
        new("Charlotte_Dress",                            "Charlotte"),
        new("Charlotte_BNikini",                          "Charlotte"),
        new("Charlotte_Agentbust",                        "Charlotte"),
        new("Charlotte_ChristmasDressBust",               "Charlotte"),
        new("Charlotte_BirthdayOutfit",                   "Charlotte"),
        new("Charlotte_PirateOutfit_Bust",                "Charlotte"),
        new("Charlotte_RedBikini",                        "Charlotte"),
        new("ClaudiaBust_Default",                        "Claudia"),
        new("ClaudiaBust_StarCon",                        "Claudia"),
        new("Claudia_StreetinterviewBust",                "Claudia"),
        new("Choe_Base",                                  "Choe"),
        new("Choe_Nude",                                  "Choe"),
        new("Tasha_Default",                              "Tasha"),
        new("NyxaraBust_Default",                         "Nyxara"),
        new("NyxaraBust_WorkerBust",                      "Nyxara"),
        new("NyxaraBust_Dark",                            "Nyxara"),
        new("Josef",                                      "Josef"),
        new("Josef_sprot",                                "Josef"),
        new("JosefSmoking",                               "Josef"),
        new("JosefDout",                                  "Josef"),
        new("Josef_ChristmasBust",                        "Josef"),
        new("Josef_HalloweenBust",                        "Josef"),
        new("Josef_CasualShirtBust",                      "Josef"),
        new("Adrian_bust",                                "Adrian"),
        new("Adrian_Suit",                                "Adrian"),
        new("Adrian_Sport",                               "Adrian"),
        new("Adrian_SemiNude",                            "Adrian"),
        new("Adrian_HalloweenBust",                       "Adrian"),
        new("Isabella",                                   "Isabella"),
        new("Isabella_Swimsuit",                          "Isabella"),
        new("Isabella_Lingerie",                          "Isabella"),
        new("Sofia_Police",                               "Sofia"),
        new("Sofia_Undercover",                           "Sofia"),
        new("Sofia_Nude",                                 "Sofia"),
        new("Sofia_Dress",                                "Sofia"),
        new("Sofia_Slut",                                 "Sofia"),
        new("Sofia_Cow",                                  "Sofia"),
        new("Sofia_Lingerie",                             "Sofia"),
        new("Katarina_Normal",                            "Katarina"),
        new("Katarina_Nude",                              "Katarina"),
        new("Katarina_Swimwear",                          "Katarina"),
        new("Katarina_Cowbust",                           "Katarina"),
        new("Emma_Normal",                                "Emma"),
        new("Emma_Swimwear",                              "Emma"),
        new("Emma_Nude",                                  "Emma"),
        new("Emma_Lingerie",                              "Emma"),
        new("Emma_Cowbust",                               "Emma"),
        new("NurseNina_Default",                          "NurseNina"),
        new("Emma_Towel",                                 "Emma"),
        new("Mario_Normal",                               "Mario"),
        new("Mario_Nude",                                 "Mario"),
        new("Master_Default",                             "Master"),
        new("Nadia_RedSwimsuitBust",                      "Nadia"),
        new("Haniya",                                     "Haniya"),
        new("Haniya_dress",                               "Haniya"),
        new("Haniya_bunnysuit",                           "Haniya"),
        new("Haniya_nude",                                "Haniya"),
        new("Haniya_CasualBust",                          "Haniya"),
        new("XXX_Celeste_Bust",                           "Celeste"),
        new("Rockerguy_Bust",                             "Rockerguy"),
        new("TomboyToni_BustDefault",                     "Toni"),
        new("TomboyToni_BustCutie",                       "Toni"),
        new("TomboyToni_BustBaroutfit",                   "Toni"),
        new("TomboyToni_Newyearsdressbust",               "Toni"),
        new("TomboyToni_BustDefaultCLEAN",                "Toni"),
        new("River_Base",                                 "River"),
        new("River_Dress",                                "River"),
        new("River_Lingerie",                             "River"),
        new("Kate",                                       "Kate"),
        new("KateUndies",                                 "Kate"),
        new("KateDress",                                  "Kate"),
        new("KatePullover",                               "Kate"),
        new("KateBikini",                                 "Kate"),
        new("Kateninjabust",                              "Kate"),
        new("KateCasualShirtbust",                        "Kate"),
        new("Amelia_defaultbust",                         "Amelia"),
        new("Amelia_Barista",                             "Amelia"),
        new("Amelia_Beach",                               "Amelia"),
        new("Amelia_Carwash",                             "Amelia"),
        new("Amelia_NewYearsEveBust",                     "Amelia"),
        new("Amelia_Cowbust",                             "Amelia"),
        new("Amelia_BaristaMilkyBust",                    "Amelia"),
        new("Amelia_BrownJacketBust",                     "Amelia"),
        new("Ken",                                        "Ken"),
        new("Ken_D_Out",                                  "Ken"),
        new("Ken_Swimsuit",                               "Ken"),
        new("Zuri",                                       "Zuri"),
        new("Zuri_CasualBarBust",                         "Zuri"),
        new("Zuri_MotelBust",                             "Zuri"),
        new("AliceBust",                                  "Alice"),
        new("AliceDress",                                 "Alice"),
        new("AliceSexy",                                  "Alice"),
        new("AliceSwimwear",                              "Alice"),
        new("Alice_GhostBust",                            "Alice"),
        new("Alice_GhostFaceOutBust",                     "Alice"),
        new("NorahDefault_Bust",                          "Norah"),
        new("NorahWhiteBikiniBust",                       "Norah"),
        new("SamuelMalePastor_Bust",                      "Samuel"),
        new("SamuelSwimBust",                             "Samuel"),
        new("Gabriel_Bust",                               "Gabriel"),
        new("SamanthaBust",                               "Samantha"),
        new("Samantha_Swimsuit",                          "Samantha"),
        new("Samantha_SwimsuitSlutty",                    "Samantha"),
        new("Samantha_Nude",                              "Samantha"),
        new("Samantha_Gaming",                            "Samantha"),
        new("SamanthaBust_ComfyCasualOutside",            "Samantha"),
        new("PhoenixBust",                                "Phoenix"),
        new("Phoenixbust_Casual",                         "Phoenix"),
        new("PhoenixBust_Suit",                           "Phoenix"),
        new("PhoenixBust_Swimsuit",                       "Phoenix"),
        new("JoeyBust",                                   "Joey"),
        new("JoeyCoolCasualBust",                         "Joey"),
        new("HimariBust",                                 "Himari"),
        new("Himari_Beachbust",                           "Himari"),
        new("Himari_SexySweaterBust",                     "Himari"),
        new("HimariMotherBust",                           "Himari (Mother)"),
        new("HimariMotherBustRoseLingerie",               "Himari (Mother)"),
        new("HimariFatherBust",                           "Himari (Father)"),
        new("KirbyBustDefault",                           "Kirby"),
        new("KirbyBustNude",                              "Kirby"),
        new("KirbyBustNCowgirl",                          "Kirby"),
        new("KirbyBustCasualOutfit",                      "Kirby"),
        new("S_ClayDefaultBust",                          "Clay"),
        new("Robert_Bust",                                "Robert"),
        new("AstridStoreBust",                            "Astrid"),
        new("AstridPinkBikiniBust",                       "Astrid"),
        new("Astrid_CasualRed_Bust",                      "Astrid"),
        new("LizBust",                                    "Liz"),
        new("doctorfrost_default",                        "Doctor Frost"),
        new("doctorfrost_default_PReg",                   "Doctor Frost"),
        new("doctorfrost_Casualbust",                     "Doctor Frost"),
        new("doctorfrost_Casualbust_Preg",                "Doctor Frost"),
        new("doctorfrost_bdsm",                           "Doctor Frost"),
        new("doctorfrost_privatelabbust",                 "Doctor Frost"),
        new("doctorfrost_privatelab_Pregbust",            "Doctor Frost"),
        new("Vanessa_Bust_Nun",                           "Vanessa"),
        new("Vanessa_Bust_LibraryOutfit",                 "Vanessa"),
        new("S_Bouncer",                                  "Bouncer"),
        new("S_Elbandito",                                "El Bandito"),
        new("S_ShadyVendor",                              "Shady Vendor"),
        new("S_ShadyVendor_BathrobeBust",                 "Shady Vendor"),
        new("S_HarborCopBust",                            "Harbor Cop"),
        new("Richwomanblonde",                            "Rich Woman (Blonde)"),
        new("Richwomanpink",                              "Rich Woman (Pink)"),
        new("Richguy",                                    "Rich Guy"),
        new("Jasper_Default",                             "Jasper"),
        new("Roxy_Default",                               "Roxy"),
        new("V_ChihiroDefault",                           "Chihiro (Vacation)"),
        new("V_FreyaDefault",                             "Freya (Vacation)"),
        new("V_LiamDefault",                              "Liam (Vacation)"),
        new("V_LeilaniDefault",                           "Leilani (Vacation)"),
        new("V_LeilaniBikiniBust",                        "Leilani (Vacation)"),
        new("V_MeiDefault",                               "Mei (Vacation)"),
        new("V_MeiRedDress",                              "Mei (Vacation)"),
        new("V_MeiNude",                                  "Mei (Vacation)"),
        new("V_MichelleDefault",                          "Michelle (Vacation)"),
        new("V_RikuDefault",                              "Riku (Vacation)"),
        new("V_SakuraDefault",                            "Sakura (Vacation)"),
        new("V_S_JudgeBenjamin",                          "Judge Benjamin (Vacation)"),
        new("V_S_Toshiro",                                "Toshiro (Vacation)"),
        new("V_S_Daiju",                                  "Daiju (Vacation)"),
        new("V_S_Hiroji",                                 "Hiroji (Vacation)"),
        new("V_S_Sora",                                   "Sora (Vacation)"),
        new("V_S_Diego",                                  "Diego (Vacation)"),
        new("V_S_Clara",                                  "Clara (Vacation)"),
        new("V_S_Felix",                                  "Felix (Vacation)"),
        new("V_S_CrazyOldMan",                            "Crazy Old Man (Vacation)"),
        new("V_S_Wolfguy",                                "Wolfguy (Vacation)"),
        new("V_S_Wolfgirl",                               "Wolfgirl (Vacation)"),
        new("S_Carina",                                   "Carina"),
        new("S_Elfina",                                   "Elfina"),
        new("S_FanBlueShirt",                             "Fan: Blue Shirt"),
        new("S_FanAsian",                                 "Fan: Asian"),
        new("S_FanGirl",                                  "Fan: Girl"),
        new("S_FanOldMan",                                "Fan: Old Man"),
        new("S_FanFemboy",                                "Fan: Femboy"),
        new("S_FanMuscle",                                "Fan: Muscle"),
        new("S_FanJeff",                                  "Fan: Jeff"),
        new("S_ParkWoman1",                               "Park Woman"),
        new("S_ParkMan",                                  "Park Man"),
        new("S_Mobster1",                                 "Mobster 1"),
        new("S_Mobster2",                                 "Mobster 2"),
        new("S_Technician",                               "Technician"),
        new("S_Blackguy",                                 "Black Guy"),
        new("S_Ghost",                                    "Ghost"),
        new("S_CelesteAgent",                             "Celeste Agent"),
        new("S_Trenchcoatmilfbust",                       "Trenchcoat MILF"),
        new("S_LadyNoireBust",                            "Lady Noire"),
        new("S_Flowercustomer",                           "Flower Customer"),
        new("S_Succubus",                                 "Succubus"),
        new("S_RedDemon",                                 "Red Demon"),
        new("S_AnnaMummyOutfit",                          "Anna (Mummy Outfit)"),
        new("S_Nightheart",                               "Nightheart"),
        new("S_PopPop",                                   "PopPop"),
        new("S_RichCEOBust",                              "Rich CEO"),
        new("S_Minitalk_NPC_DowntownBlonde",              "Downtown Blonde"),
        new("S_Minitalk_NPC_BigButtCityWoman",            "Big-Butt City Woman"),
        new("S_Minitalk_NPC_CityGingerGlasse",            "City Ginger Glasses"),
        new("S_Minitalk_NPC_RedShirtCityGuy",             "Red-Shirt City Guy"),
        new("S_Minitalk_NPC_ShyCityGuy",                  "Shy City Guy"),
        new("S_Minitalk_NPC_OldCityGentleman",            "Old City Gentleman"),
        new("S_Minitalk_NPC_ChubbyBackpackGuy",           "Chubby Backpack Guy"),
        new("S_Minitalk_NPC_RedhairMaleModel",            "Redhair Male Model"),
        new("S_Minitalk_NPC_NeonRowPinkWorker",           "Neon Row Pink Worker"),
        new("S_Minitalk_NPC_BlondeNeonRowWorker",         "Blonde Neon Row Worker"),
        new("S_Minitalk_NPC_UsedBoobaWorker",             "Used-Booba Worker"),
        new("S_Minitalk_NPC_AverageWoman",                "Average Woman"),
        new("S_Minitalk_NPC_RichCustomerFemale",          "Rich Customer (Female)"),
        new("S_Minitalk_NPC_KateFriend",                  "Kate's Friend"),
        new("S_BigFootBust",                              "BigFoot"),
        new("S_LizardGuyBust",                            "Lizard Guy"),
        new("S_Evelyn_AlienBust",                         "Evelyn (Alien)"),
        new("S_Poolchick_Blonde",                         "Pool Chick (Blonde)"),
        new("S_Poolchick_Reddie",                         "Pool Chick (Reddie)"),
        new("S_Bust_Mini_Mallwaifu_BlueHair",             "Mall Waifu (Blue Hair)"),
        new("S_Bust_Mini_Mallwaifu_Blonde",               "Mall Waifu (Blonde)"),
    };

    /// <summary>Lookup by GO name. Returns null if the name isn't in the catalog.</summary>
    public static VanillaBust? FindByGoName(string goName)
    {
        foreach (var b in All)
            if (b.GoName == goName) return b;
        return null;
    }
}
