// <auto-generated>
//   Written by Tools/regen_vanilla_quests.py from a runtime dump of the game.
//   Regenerate it rather than editing it; see the script for what is kept and why.
// </auto-generated>
using System.Collections.Generic;

namespace SMSModForge.Model;

public static partial class VanillaQuests
{
    /// <summary>Every quest of the game's own that a pack can point at.</summary>
    public static readonly IReadOnlyList<VanillaQuest> All = new VanillaQuest[]
    {
        new("A Trained Eye (Gabriel)", "A Trained Eye (Gabriel)", false, 0, new VanillaTask[]
        {
            new(889406522, -1, "Meet Gabriel.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(612240961, 889406522, "Visit Gabriel at his Mansion in the Hiils.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Acolyte (Adrian)", "Trial by Fire (Adrian)", false, 0, new VanillaTask[]
        {
            new(472439085, -1, "Teach Adrian how to approach women.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-818926455, 472439085, "Meet Adrian at the mall.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Another Time (River", "Another Time (River)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, "Talk to River.", TaskCompletion.AnySubtask, TaskCounter.None, 0, "", false),
            new(-989935106, 1813187919, "Make time for a weekly visit to the park.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(400938478, -1, "Ask River to come over.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-210829219, 400938478, "Spend some quality time with River.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Astrid Quest", "Into the Dark (Astrid)", false, 0, new VanillaTask[]
        {
            new(276722473, -1, "Meet with Astrid.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1321869430, 276722473, "Lady Noire's Lair is near the harbor.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1890282631, 276722473, "Astrid is waiting there on Friday.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1745766144, -1, "Help Astrid find whatever she is looking for.", TaskCompletion.SubtasksInSequence, TaskCounter.Value, 3, "", false),
            new(-537750574, 1745766144, "Meet Astrid at the abandoned house on a Friday.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(2076169433, -1, "Go back home.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(700721478, 2076169433, "I have the feeling someone's waiting for me.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Behind The Looking Glass (Alice)", "Behind The Looking Glass (Alice)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, "Hit the club and see who shows up.", TaskCompletion.AnySubtask, TaskCounter.None, 0, "", false),
            new(-989935106, 1813187919, "Head to the club on Friday.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(400938478, -1, "Get past the bouncer. ", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-210829219, 400938478, "Maybe someone at the mall can teach me some slang.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(2044070570, -1, "Hang out with Alice and see where things go.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-1235282320, 2044070570, "Turn up the heat and make her melt on the dancefloor.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-1286401561, -1, "To be continued...", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Bishop (Mario)", "Bishop (Mario)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, "Help Mario compare files", TaskCompletion.AnySubtask, TaskCounter.None, 0, "", false),
            new(-989935106, 1813187919, "Visit Mario once a week.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1315981684, -1, "Push Katarina past her limits.", TaskCompletion.AnySubtask, TaskCounter.None, 0, "", false),
            new(-1759660069, 1315981684, "Visit Mario.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1410719678, -1, "Corrupt Emma.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1070760953, 1410719678, "Visit the sauna every week.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Codebreaker (Samantha)", "Codebreaker (Samantha)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, "Start hacking lessons with Sam.", TaskCompletion.AnySubtask, TaskCounter.Property, 5, "Traits[Hacker]", false),
            new(-989935106, 1813187919, "Talk with Samantha at her place weekly.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Cold Logic (Dr. Frost)", "Cold Logic (Doctor Frost)", false, 0, new VanillaTask[]
        {
            new(856343042, -1, "Find Dr. Frost's secret lab.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(2074802715, 856343042, "Her lab should be at the harbor.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(912427419, -1, "Research all three of Dr. Frost's formulas", TaskCompletion.SubtasksInSequence, TaskCounter.Value, 3, "", false),
            new(1583514607, 912427419, "This is quite the hard task to complete...", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1102123644, 912427419, "I should search Peak City for a vampire.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(848535213, 912427419, "I should search a snowy location for a werewolf.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1151313953, 912427419, "I probably already met someone divine, someone celestial.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-1459919121, -1, "To be continued...", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Collab (Chloe)", "Collab (Chloe)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, "Set up a meeting with Chloe.", TaskCompletion.AnySubtask, TaskCounter.None, 0, "", false),
            new(-989935106, 1813187919, "Go see Chloe at her place in the Hills.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(400938478, -1, "Start the collaboration with Chloe.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-210829219, 400938478, "Visit Chloe on Wednesday.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Cryptids (Emma)", "Weirder Things (Emma)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, "Join Emma to look for signs of Bigfoot.", TaskCompletion.AnySubtask, TaskCounter.None, 0, "", false),
            new(-989935106, 1813187919, "Meet Emma in the city on Tuesday.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(400938478, -1, "Check out reports of the lizard creature.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-210829219, 400938478, "Meet Emma in the city on Tuesday.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-342992218, -1, "Investigate the vampire rumors.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1942567620, -342992218, "Meet Emma in the city on Tuesday.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Debt", "<color=#ffd257>The Debt", false, -25, new VanillaTask[]
        {
            new(1813187919, -1, "Find a way to deal with Josef’s debt.", TaskCompletion.AnySubtask, TaskCounter.None, 0, "", false),
            new(-989935106, 1813187919, "Support Josef in paying off what he owes.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-1675646997, 1813187919, "Or find a way to push Josef out.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Dinner Boyfriend (Himari)", "A Convincing Lie (Himari)", false, 0, new VanillaTask[]
        {
            new(1070060591, -1, "Get through the first dinner.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(351069880, 1070060591, "I can visit Himari once a week using the garage elevator.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1043518098, -1, "Get through the second dinner.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-920827797, 1043518098, "Still don’t screw it up.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(2131395796, -1, "Get through the last dinner.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1071521521, 2131395796, "Prove your worth in front of her parents.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Explore The City", "<color=#ffd257>The World Just Got Bigger", false, -15, new VanillaTask[]
        {
            new(1802849953, -1, "Explore Peak City", TaskCompletion.SubtasksInCombination, TaskCounter.Value, 3, "", false),
            new(-1625034000, 1802849953, "Visit the Mall", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-2014205567, 1802849953, "Visit the Beach", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-1798439349, 1802849953, "Visit the Park", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Fanboy (Ken)", "Fanboy (Ken)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, " Go over Ken's email.", TaskCompletion.AnySubtask, TaskCounter.None, 0, "", false),
            new(-989935106, 1813187919, "Speak with Anna in the kitchen.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(400938478, -1, "Have a conversation with Ken.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-210829219, 400938478, "Go to the suburbs and meet Ken.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-25251400, -1, "Keep an eye on Ken’s meeting with Anna.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-1160666087, -25251400, "Be at your front door to meet Ken on Thursday.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Flowers (Zhen)", "Flowers (Zhen)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, "Look for someone with gardening skills.", TaskCompletion.AnySubtask, TaskCounter.None, 0, "", false),
            new(-989935106, 1813187919, "Talk to Anna about helping with the garden.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(400938478, -1, "Go back to Zhen.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-210829219, 400938478, "Visit Zhen and speak with him at the shrine.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Gabriel Training", "Photography Lessons (Gabriel)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, "Finish Gabriel’s first set of lessons.", TaskCompletion.AnySubtask, TaskCounter.None, 0, "", false),
            new(-989935106, 1813187919, "Meet Gabriel every Tuesday.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(906894481, -1, "Stop by Gabriel’s place.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-1804474480, 906894481, "Give Gabriel some time before returning.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-200401361, -1, " Look for a model who’s not Anna.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1437005603, -200401361, "Search the mall for someone willing to model.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-1612451931, -1, "Visit Kate.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-1484399764, -1612451931, "Visit Kate's place on Thursday.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-619506573, -1, "Earn Kate’s trust and make her feel safe.", TaskCompletion.AnySubtask, TaskCounter.Value, 3, "", false),
            new(1780373763, -619506573, "Kate could be at the beach, the bar or the park.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-1146633850, -619506573, "Thursday is her free day.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(996623161, -1, "Visit Kate and take the photo.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(626310357, 996623161, "Make sure it's her free day.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-1632000952, -1, "Finish Gabriel’s follow-up lessons.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1917495845, -1632000952, "Bring Kate’s photo to Gabriel for feedback.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-2003788056, -1, "Finish Gabriel’s last teaching session.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1270318540, -2003788056, "Pass Gabriel’s ultimate photography challenge.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Gains (Phoneix", "Gains (Phoenix)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, "Finish a full session of Phoenix’s standard training.", TaskCompletion.AnySubtask, TaskCounter.Value, 5, "", false),
            new(-989935106, 1813187919, "Complete five regular training sessions with Phoenix.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(400938478, -1, "Finish one of Phoenix’s advanced training sessions.", TaskCompletion.SubtasksInSequence, TaskCounter.Value, 5, "", false),
            new(-210829219, 400938478, "Complete five special training sessions with Phoenix.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Going Live (Anna)", "Going Live (Anna)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, "Look for someone who knows their way around tech.", TaskCompletion.AnySubtask, TaskCounter.None, 0, "", false),
            new(-989935106, 1813187919, "Speak with Joey about the issue.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(400938478, -1, "Track down the local mechanic.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-210829219, 400938478, "Head out to the Badlands.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1734583375, -1, "Find a way to get Toni out.", TaskCompletion.SubtasksInSequence, TaskCounter.Value, 3, "", false),
            new(-1627642807, 1734583375, "Win three cum races.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1569370815, -1, "Return to Anna.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-1094926156, 1569370815, "Talk to Anna at the Studio.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Going Viral (Anna)", "<color=#ffd257>Starmaker", false, -50, new VanillaTask[]
        {
            new(1813187919, -1, "Reach 50 subscribers on Anna’s page.", TaskCompletion.AnySubtask, TaskCounter.Property, 50, "Core[Subscriber]", false),
            new(-989935106, 1813187919, "Keep photographing Anna to build content.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(400938478, -1, "See what Anna has waiting in the wardrobe.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-210829219, 400938478, " Go to the wardrobe upstairs and meet Anna there.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(334225886, -1, "Grow Anna’s Starmaker page to 1,000 subscribers while helping her feel more comfortable around you.", TaskCompletion.SubtasksInSequence, TaskCounter.Property, 1000, "Core[Subscriber]", false),
            new(-1720742330, 334225886, "Take plenty of photos of Anna.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-1381768894, -1, "Spend more time with Anna. Help her to open up.", TaskCompletion.SubtasksInSequence, TaskCounter.Property, 4, "Events_11[Anna-ComfyDates]", false),
            new(2051310763, -1381768894, "Spend time with Anna at the Mall on Friday.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1587097261, -1381768894, "Spend time with Anna at the Beach on Tuesday.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-1871564337, -1381768894, "Spend time with Anna at the Park on Wednesday.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1187244151, -1, "Talk to Anna.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1829094963, 1187244151, "I should head home. Anna wants to tell me something.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-1034943688, -1, "See what Anna has prepared for you.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-1819202415, -1034943688, "Head to the studio during the morning.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-274551123, -1, "Grow Anna's Starmaker page to 2,500 subscribers", TaskCompletion.SubtasksInSequence, TaskCounter.Property, 2500, "Core[Subscriber]", false),
            new(641073902, -274551123, "Take plenty of photos of Anna", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1689069395, -1, "Check in on Anna.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(795980437, 1689069395, "Maybe Anna will say something in the Studio.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-1516807890, -1, "Seduce Anna.", TaskCompletion.SubtasksInSequence, TaskCounter.Property, 5, "Mainstory[horny-m]", false),
            new(-1511511112, -1516807890, "Put your hands on her and watch her give in.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-283368465, -1, "Visit the Studio.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-202414027, -283368465, "Ask Anna to pose with your cock in full view.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Gold and Wine (Charlotte)", "Gold And Wine (Charlotte)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, "Build a connection with Charlotte.", TaskCompletion.AnySubtask, TaskCounter.None, 0, "", false),
            new(-989935106, 1813187919, "Meet Charlotte on her yacht each Monday.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Heavenly Husband (Himari) OUTDATED", "Heavenly Husband (Himari)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, "Reveal the truth to Himari", TaskCompletion.AnySubtask, TaskCounter.None, 0, "", false),
            new(-989935106, 1813187919, "Become a heavenly husband and confront Himari", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Inner Regret", "<color=#ffd257>Inner Regret", false, -5, new VanillaTask[]
        {
            new(1813187919, -1, "Support Anna and help her recover emotionally.", TaskCompletion.AnySubtask, TaskCounter.None, 0, "", false),
            new(-989935106, 1813187919, "Speak with Anna when she’s drinking in the kitchen.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-649791451, 1813187919, "Be there for Anna and try to pull her back up.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(871721791, 1813187919, "Or don't...", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Just A Drink (Liz)", "Just A Drink (Liz)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, "Hang out with Liz and see where things go.", TaskCompletion.AnySubtask, TaskCounter.None, 0, "", false),
            new(-989935106, 1813187919, " Meet up at the bar each Tuesday night.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(400938478, -1, "Spend time with both Anna and Liz.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-210829219, 400938478, "Head to the hotel.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Justice (Sofia)", "Justice (Sofia)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, "Search for proof that can be used against Mario.", TaskCompletion.AnySubtask, TaskCounter.None, 0, "", false),
            new(-989935106, 1813187919, "Assist Sofia in her case against Mario.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-366986634, 1813187919, "Or betray Sofia and warn Mario instead.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(400938478, -1, "Check back in with Sofia.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-210829219, 400938478, "Meet Sofia at the gas station on Friday.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Lonely (Samantha)", "Lonely (Samantha)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, "Break through her walls and earn her trust.", TaskCompletion.AnySubtask, TaskCounter.Property, 3, "Core[samantha-seduction]", false),
            new(-989935106, 1813187919, "Spend Mondays with Samantha at the beach.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-1940267206, 1813187919, "Bring body oil and give Samantha a sensual massage.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-1336846769, -1, "Turn up the charm and seduce Sam.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-196740262, -1336846769, "Stop by Samantha’s house and spend time with her.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(926414583, -1336846769, "She’s in the living room on Tuesday and Friday.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Moo! (Kirby)", "Moo! (Kirby)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, "Introduce yourself to Kirby.", TaskCompletion.AnySubtask, TaskCounter.None, 0, "", false),
            new(-989935106, 1813187919, "Go to Kirby’s farm and check it out.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(400938478, -1, "Figure out how to start milk production.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-210829219, 400938478, "Speak with Dr. Frost about lactation methods.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(13458008, -1, "Head back to Kirby with what you’ve learned.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-995475353, 13458008, "Visit the farm again and continue helping.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(837760614, -1, "Help Kirby get the dairy running successfully.", TaskCompletion.SubtasksInSequence, TaskCounter.Property, 5, "Milking Save[bafa-totalmilksold]", false),
            new(708891727, 837760614, "Maintain steady milk production.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Mura Quest", "The Other Side of Science (Dr. Mura)", false, 0, new VanillaTask[]
        {
            new(2122219745, -1, "Talk to Dr. Mura.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(685928625, 2122219745, "I discovered that he is held prisoner by Evelyn. ", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-2142819677, -1, "To be continued...", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("No Going Back (Anna)", "<color=#ffd257>Point of No Return", false, -5, new VanillaTask[]
        {
            new(-2076518017, -1, "Go to the studio and meet with Anna.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-1460210145, -2076518017, "Fuck Anna raw in the studio. No condom. No regrets.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Rival (Tristan)", "Rival (Tristan)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, "Beat Tristan at his own game.", TaskCompletion.AnySubtask, TaskCounter.None, 0, "", false),
            new(-989935106, 1813187919, "Check out different places in Peak City each Wednesday.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Secrets (Adrian)", "Secrets (Adrian)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, "Figure out how to get into Adrian’s computer.", TaskCompletion.Manual, TaskCounter.None, 0, "", false),
            new(-989935106, 1813187919, "Bypass Adrian’s security and access his files.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-673418075, 1813187919, "Purchase a tool that can help break into his system.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1219308889, 1813187919, "Start learning how to hack it yourself.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-96231176, 1813187919, "Reach five stars with Anna.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-968853259, -1, "Speak with Anna about Adrian.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-819227118, -968853259, "Tell Anna what you found on Adrian’s PC.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1045841325, -968853259, "Talk to her in the Kitchen.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-1312943876, -1, "Check on Anna and Adrian.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-650557138, -1312943876, "Anna should in Adrian's room on Friday.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1450006868, -1312943876, "I should try to help Adrian to man up.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-428629646, -1312943876, "This will take some time...", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-643516662, -1, "Check the Bathroom.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-150770455, -643516662, "Adrian should be more confident now.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Starborn (Celeste)", "Starborn (Celeste)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, "Arrange a meeting with Starmaker’s top model.", TaskCompletion.AnySubtask, TaskCounter.None, 0, "", false),
            new(-989935106, 1813187919, "Head to the abandoned theme park.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(400938478, -1, "Try to persuade Celeste to support Anna’s rise.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-210829219, 400938478, "Grow Anna’s Starmaker page to 30,000 subscribers.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(2006288451, 400938478, "Set up a livestream session for Anna.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-1666833946, 400938478, "Support Anna and help her recover emotionally.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(547053281, -1, "Arrange a meeting with Celeste.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-356840676, 547053281, "Find Celeste at the Starcon event.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1358935201, -1, "Speak privately with Celeste.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1236349690, 1358935201, "Try to talk Celeste into stepping aside.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1029245597, 1358935201, "... Or destroy Celeste’s image.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Starcon", "Starcon (Anna)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, "Attend the Starcon event.", TaskCompletion.AnySubtask, TaskCounter.None, 0, "", false),
            new(-989935106, 1813187919, "Go to Starcon with Anna during the weekend.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Techbro (Joey)", "Techbro (Joey)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, "Talk to Zuri.", TaskCompletion.AnySubtask, TaskCounter.None, 0, "", false),
            new(-989935106, 1813187919, "Get Zuri to investigate the restroom.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(400938478, -1, "See how Zuri’s doing after the prank.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-210829219, 400938478, "Go to the restroom where the prank is set up.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("The Moment of Truth (Josef)", "Moment of Truth (Josef)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, "Meet Josef at the door each Friday.", TaskCompletion.AnySubtask, TaskCounter.None, 0, "", false),
            new(-989935106, 1813187919, "Pick up beer before talking to Josef.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-368520077, 1813187919, "Gain Josef’s trust.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1806912568, 1813187919, "... Or use Josef’s weakness to your advantage.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Vanessa Quest", "Holy Temptation (Vanessa)", false, 0, new VanillaTask[]
        {
            new(2105965574, -1, "Spend time with Vanessa.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-359344693, 2105965574, "You can study with her once a week at the Library.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-413582714, -1, "Help Vanessa to open up.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(556514677, -413582714, "I should talk to her at church.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
        new("Virile (Isabella)", "Virile (Isabella)", false, 0, new VanillaTask[]
        {
            new(1813187919, -1, "Go to the meeting with Isabella.", TaskCompletion.AnySubtask, TaskCounter.None, 0, "", false),
            new(-989935106, 1813187919, "Show up at the hotel to meet Isabella on Thursday.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(1822478026, 1813187919, "Let Josef know I’m meeting his ex… or don’t.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(400938478, -1, "Breed her like she asked.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
            new(-210829219, 400938478, "Keep showing up and fucking her every Thursday.", TaskCompletion.SubtasksInSequence, TaskCounter.None, 0, "", false),
        }),
    };
}
