namespace SMSModForge.Shared
{
    /// <summary>
    /// How the game's own characters speak: the face they can pull, the voice
    /// they pull it in, and the colour their name is written in.
    /// <para/>
    /// GENERATED by Tools/regen_vanilla_speech.py from two dumps taken out of
    /// a running game -- see that file for what they are and how to take them.
    /// Do not edit by hand.
    /// <para/>
    /// None of this is readable from the game's files. The Actor assets carry
    /// no references an extractor can follow, and the name colours live in a
    /// private list on a component that does not exist until a conversation
    /// has started.
    /// <para/>
    /// Compiled into both projects, for the usual reason: the editor offers an
    /// author a character's real defaults, and the runtime has to reproduce
    /// them. Two copies would drift the first time the game changed one.
    /// <para/>
    /// 84 of the game's characters are here; 54 can pull a
    /// face and 36 have a name colour of their own. The rest of the
    /// cast is in <see cref="VanillaCastData"/>: a bust in a crowd is a
    /// character an author can dress, but not one the game gave a voice.
    /// </summary>
    public static class VanillaSpeech
    {
        /// <summary>One of the game's characters, as a speaker.</summary>
        public sealed class Speaker
        {
            public Speaker(string key, string name, string expressionVariable,
                           string expressions, bool useTypewriter, int frequency,
                           float pitchMin, float pitchMax, string gibberish,
                           string speechSkin, string nameColor)
            {
                Key = key;
                Name = name;
                ExpressionVariable = expressionVariable;
                UseTypewriter = useTypewriter;
                Frequency = frequency;
                PitchMin = pitchMin;
                PitchMax = pitchMax;
                Gibberish = gibberish;
                SpeechSkin = speechSkin;
                NameColor = nameColor;

                var names = new System.Collections.Generic.List<string>();
                // Case-insensitively, because an author types these names.
                var values = new System.Collections.Generic.Dictionary<string, int>(
                    System.StringComparer.OrdinalIgnoreCase);
                if (!string.IsNullOrEmpty(expressions))
                {
                    foreach (string pair in expressions.Split(' '))
                    {
                        int split = pair.LastIndexOf('=');
                        if (split <= 0) continue;
                        string id = pair.Substring(0, split);
                        int value;
                        if (!int.TryParse(pair.Substring(split + 1), out value)) continue;
                        names.Add(id);
                        values[id] = value;
                    }
                }
                Expressions = names.ToArray();
                _values = values;
            }

            /// <summary>The editor's key for this character.</summary>
            public string Key { get; private set; }

            /// <summary>What the game calls them out loud.</summary>
            public string Name { get; private set; }

            /// <summary>
            /// The number, under the <c>Expressions</c> global-name variable
            /// asset, that decides which face this character is wearing --
            /// or null for a character the game never gave one.
            /// <para/>
            /// Every bust on screen carries a trigger watching for a
            /// global-name variable change; on one, it copies its own
            /// character's number into <c>Currently-Chosen</c> and switches the
            /// matching child of <c>Expressions</c> on. So switching a child on
            /// by hand lasts exactly until the next global variable is written,
            /// anywhere, by anything. Setting this is how a face stays.
            /// </summary>
            public string ExpressionVariable { get; private set; }

            /// <summary>The faces this character has, as the game names them.
            /// Empty for a character with none configured.</summary>
            public string[] Expressions { get; private set; }

            private readonly System.Collections.Generic.Dictionary<string, int> _values;

            /// <summary>The number that means this face, or -1 for a name this
            /// character does not have.</summary>
            public int ValueOf(string expression)
            {
                int value;
                return expression != null && _values.TryGetValue(expression, out value)
                     ? value : -1;
            }

            /// <summary>Whether the game types this character's lines out.</summary>
            public bool UseTypewriter { get; private set; }

            /// <summary>Characters per second.</summary>
            public int Frequency { get; private set; }

            /// <summary>The pitch range the gibberish clip is played at. This is
            /// what makes one character sound unlike another.</summary>
            public float PitchMin { get; private set; }

            /// <summary>The top of that range.</summary>
            public float PitchMax { get; private set; }

            /// <summary>The audio clip the typewriter chirps, by name, or null
            /// for GC2's own default.</summary>
            public string Gibberish { get; private set; }

            /// <summary>The speech skin this character overrides to, or null for
            /// whichever one the conversation is using.</summary>
            public string SpeechSkin { get; private set; }

            /// <summary>The colour the game writes this name in, as #RRGGBB, or
            /// null for the ordinary one.</summary>
            public string NameColor { get; private set; }
        }

        /// <summary>Every character the game gave a voice, in catalog order.</summary>
        public static readonly Speaker[] All =
        {
            new Speaker("anna", "Anna", "M-expression", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 45, 1f, 1.5f, "Pixel Jump 03", "AnnaSpeech", "#FFDF7C"),
            new Speaker("nikki", "Nikki", "Nikki", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1f, 1.5f, "Pixel Jump 03", null, null),
            new Speaker("cerise", "Cerise", "android", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 0.9f, 1.3f, "Pixel Jump 03", null, "#649FFF"),
            new Speaker("charlotte", "Charlotte", "Charlotte", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 0.9f, 1.3f, "Pixel Jump 03", null, "#C1FF99"),
            new Speaker("claudia", "Claudia", "newsanchor", "neutral=0 talk=1",
                        true, 25, 1.2f, 1.5f, "Pixel Jump 03", null, null),
            new Speaker("chloe", "Chloe", "Chloe", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 0.9f, 1.3f, "Pixel Jump 03", null, null),
            new Speaker("tasha", "Tasha", "tasha", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1.2f, 1.5f, "Pixel Jump 03", null, "#FFF4A2"),
            new Speaker("nyxara", "Nyxara", "nyxara", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1.2f, 1.5f, "Pixel Jump 03", null, "#BA6DFF"),
            new Speaker("josef", "Josef", "D-Expression", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 40, 0.4f, 0.7f, "Pixel Jump 03", "MaleSpeech", "#FFB999"),
            new Speaker("adrian", "Adrian", "B-Expression", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 40, 0.8f, 1.2f, "Pixel Jump 03", "MaleSpeech", "#99C5FF"),
            new Speaker("isabella", "Isabella", "Isabella-Expression", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1f, 1.5f, "Pixel Jump 03", null, "#CA984D"),
            new Speaker("sofia", "Sofia", "sofia", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1f, 1.5f, "Pixel Jump 03", null, "#7E9EFF"),
            new Speaker("katarina", "Katarina", "katarina", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1f, 1.5f, "Pixel Jump 03", null, "#FF8DB5"),
            new Speaker("emma", "Emma", "emma", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1f, 1.5f, "Pixel Jump 03", null, "#A5DEFF"),
            new Speaker("nursenina", "Nurse Nina", "nurse", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1f, 1.5f, "Pixel Jump 03", null, "#FFA2E5"),
            new Speaker("mario", "Mario", "mario", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 40, 0.4f, 0.7f, "Pixel Jump 03", "MaleSpeech", "#BFC1FF"),
            new Speaker("masterzhen", "Master Zhen", "master-j", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 40, 0.6f, 1f, "Pixel Jump 03", "MaleSpeech", null),
            new Speaker("nadia", "Nadia", null, "",
                        true, 25, 0.8f, 1.4f, "Pixel Jump 03", null, null),
            new Speaker("haniya", "Haniya", "Haniya-expression", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1f, 1.5f, "Pixel Jump 03", null, "#D6783C"),
            new Speaker("celeste", "Celeste", "Celeste", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1f, 3f, "holy church", "AnnaSpeech", "#FEFF94"),
            new Speaker("jack", "Jack", "rockerguy", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 40, 0.8f, 1.2f, "Pixel Jump 03", "MaleSpeech", null),
            new Speaker("toni", "Toni", "Tomboymech", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1.2f, 1.5f, "Pixel Jump 03", null, "#FFAD81"),
            new Speaker("river", "River", "River", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1f, 1.5f, "Pixel Jump 03", null, "#FBFFAC"),
            new Speaker("kate", "Kate", "Kate-expression", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1f, 1.5f, "Pixel Jump 03", null, "#FFB6EC"),
            new Speaker("amelia", "Amelia", "Amelia-Expression", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1f, 1.5f, "Pixel Jump 03", null, "#C7FF92"),
            new Speaker("ken", "Ken", "Ken-expression", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 0.7f, 0.9f, "Pixel Jump 03", "MaleSpeech", "#FF9C99"),
            new Speaker("zuri", "Zuri", "Zuri-expression", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1f, 1.5f, "Pixel Jump 03", null, "#C9A7FF"),
            new Speaker("alice", "Alice", "goth-expression", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1.2f, 1.5f, "Pixel Jump 03", null, "#FB99FF"),
            new Speaker("norah", "Norah", "Norah", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1f, 1.5f, "Pixel Jump 03", null, "#8FCEFF"),
            new Speaker("samuel", "Samuel", null, "",
                        true, 40, 0.3f, 0.6f, "Pixel Jump 03", "MaleSpeech", "#A8FF92"),
            new Speaker("gabriel", "Gabriel", "Gabriel-expression", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 40, 0.4f, 0.7f, "Pixel Jump 03", "MaleSpeech", "#C6FFB6"),
            new Speaker("samantha", "Samantha", "samantha-exprssion", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1f, 1.5f, "Pixel Jump 03", null, "#99FFCF"),
            new Speaker("phoenix", "Phoenix", "Phoenix-expression", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1f, 1.5f, "Pixel Jump 03", null, "#EC5151"),
            new Speaker("joey", "Joey", "joey-expression", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 40, 0.8f, 1.2f, "Pixel Jump 03", "MaleSpeech", "#A3FF99"),
            new Speaker("himari", "Himari", "himari-expression", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1f, 1.5f, "Pixel Jump 03", null, "#FF9B99"),
            new Speaker("mrskimura", "Mrs. Kimura", "Yua", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1f, 1.5f, "Pixel Jump 03", null, null),
            new Speaker("mrkimura", "Mr. Kimura", "Masaru", "neutral=0 talk=1",
                        true, 40, 0.8f, 1.2f, "Pixel Jump 03", "MaleSpeech", null),
            new Speaker("kirby", "Kirby", "Kirby", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1f, 1.5f, "Pixel Jump 03", null, "#89FA75"),
            new Speaker("clay", "Clay", "Clay", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 0.7f, 0.9f, "Pixel Jump 03", "MaleSpeech", null),
            new Speaker("robert", "Robert", "Robert", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 40, 0.4f, 0.8f, "Pixel Jump 03", "MaleSpeech", null),
            new Speaker("astrid", "Astrid", "Astrid", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1.2f, 1.5f, "Pixel Jump 03", null, "#E5595E"),
            new Speaker("liz", "Liz", "Liz-expression", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1f, 1.5f, "Pixel Jump 03", null, "#FF9B92"),
            new Speaker("doctorfrost", "Doctor Frost", "drfrost", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1.2f, 1.5f, "Pixel Jump 03", null, "#8DFFFE"),
            new Speaker("vanessa", "Vanessa", "Vanessa", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1f, 1.5f, "Pixel Jump 03", null, null),
            new Speaker("thebouncer", "The Bouncer", null, "",
                        true, 25, 0.2f, 0.5f, "Pixel Jump 03", "MaleSpeech", null),
            new Speaker("frank", "Frank", null, "",
                        true, 25, 0.2f, 0.5f, "Pixel Jump 03", "MaleSpeech", null),
            new Speaker("misszero", "Miss Zero", null, "",
                        true, 25, 1f, 1.5f, "Pixel Jump 03", null, "#6BFFF7"),
            new Speaker("cop", "Cop", null, "",
                        true, 40, 0.8f, 1.2f, "Pixel Jump 03", "MaleSpeech", null),
            new Speaker("tristan", "Tristan", null, "",
                        true, 25, 0.2f, 0.5f, "Pixel Jump 03", "MaleSpeech", null),
            new Speaker("jasper", "Jasper", "Jasper", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 40, 0.4f, 0.7f, "Pixel Jump 03", "MaleSpeech", null),
            new Speaker("roxy", "Roxy", "Roxy", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1.2f, 1.5f, "Pixel Jump 03", null, "#E25BD3"),
            new Speaker("chihiro", "Chihiro", "Chihiro", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1.2f, 1.5f, "Pixel Jump 03", null, null),
            new Speaker("freya", "Freya", "Freya", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1.2f, 1.5f, "Pixel Jump 03", null, null),
            new Speaker("liam", "Liam", "Liam", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 40, 0.4f, 0.7f, "Pixel Jump 03", "MaleSpeech", null),
            new Speaker("leilani", "Leilani", "Leilani", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1.2f, 1.5f, "Pixel Jump 03", null, null),
            new Speaker("mei", "Mei", "Mei", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1.2f, 1.5f, "Pixel Jump 03", null, null),
            new Speaker("michelle", "Michelle", "Michelle", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1.2f, 1.5f, "Pixel Jump 03", null, null),
            new Speaker("riku", "Riku", "Riku", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1.2f, 1.5f, "Pixel Jump 03", null, null),
            new Speaker("sakura", "Sakura", "Sakura", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1.2f, 1.5f, "Pixel Jump 03", null, null),
            new Speaker("toshiro", "Toshiro", null, "",
                        true, 40, 0.4f, 0.7f, "Pixel Jump 03", "MaleSpeech", null),
            new Speaker("daiju", "Daiju", null, "",
                        true, 40, 0.4f, 0.7f, "Pixel Jump 03", "MaleSpeech", null),
            new Speaker("hiroji", "Hiroji", null, "",
                        true, 40, 0.4f, 0.7f, "Pixel Jump 03", "MaleSpeech", null),
            new Speaker("sora", "Sora", null, "",
                        true, 40, 0.4f, 0.7f, "Pixel Jump 03", "MaleSpeech", null),
            new Speaker("diego", "Diego", null, "",
                        true, 40, 0.4f, 0.7f, "Pixel Jump 03", "MaleSpeech", null),
            new Speaker("clara", "Clara", null, "",
                        true, 25, 1.2f, 1.5f, "Pixel Jump 03", null, null),
            new Speaker("felix", "Felix", null, "",
                        true, 40, 0.4f, 0.7f, "Pixel Jump 03", "MaleSpeech", null),
            new Speaker("crazyoldman", "Crazy Old Man", null, "",
                        true, 25, 0.2f, 0.5f, "Pixel Jump 03", "MaleSpeech", null),
            new Speaker("carina", "Carina", null, "",
                        true, 25, 1.3f, 1.8f, "Pixel Jump 03", null, null),
            new Speaker("elfina", "Elfina", "Elfina", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1.6f, 2f, "Pixel Jump 03", "AnnaSpeech", null),
            new Speaker("technician", "Technician", null, "",
                        true, 40, 0.4f, 0.7f, "Pixel Jump 03", "MaleSpeech", null),
            new Speaker("ghost", "Ghost", "goth-expression", "neutral=0 Happy=1 Angry=2 Sad=3 Flirty=4",
                        true, 25, 1.2f, 1.5f, "Pixel Jump 03", null, null),
            new Speaker("agent", "Agent", null, "",
                        true, 25, 0.8f, 1.4f, "Pixel Jump 03", null, null),
            new Speaker("ladynoire", "Lady Noire", null, "",
                        true, 25, 0.5f, 1.5f, "Pixel Jump 03", null, "#FF5A53"),
            new Speaker("zazia", "Zazia", null, "",
                        true, 25, 0.8f, 1.4f, "Pixel Jump 03", null, null),
            new Speaker("nightheart", "Nightheart", null, "",
                        true, 25, 0.8f, 1.4f, "Pixel Jump 03", null, null),
            new Speaker("poppop", "Pop Pop", null, "",
                        true, 25, 0.2f, 0.5f, "Pixel Jump 03", "MaleSpeech", null),
            new Speaker("richceo", "Rich CEO", null, "",
                        true, 40, 0.4f, 0.7f, "Pixel Jump 03", "MaleSpeech", null),
            new Speaker("civilian", "Civilian", null, "",
                        true, 25, 1.2f, 1.5f, "Pixel Jump 03", null, null),
            new Speaker("coolguy", "Cool Guy", null, "",
                        true, 40, 0.3f, 0.6f, "Pixel Jump 03", "MaleSpeech", null),
            new Speaker("sexworker", "Sex Worker", null, "",
                        true, 40, 0.8f, 1.2f, "Pixel Jump 03", null, null),
            new Speaker("normalwoman", "Normal Woman", null, "",
                        true, 40, 0.8f, 1f, "Pixel Jump 03", null, null),
            new Speaker("richcustomer", "Rich Customer", null, "",
                        true, 25, 0.7f, 1.2f, "Pixel Jump 03", "MaleSpeech", null),
            new Speaker("megan", "Megan", null, "",
                        true, 40, 0.8f, 1.2f, "Pixel Jump 03", null, null),
            new Speaker("creature", "Creature", null, "",
                        true, 40, 0.3f, 0.6f, "Pixel Jump 03", null, null),
        };

        private static readonly System.Collections.Generic.Dictionary<string, Speaker> ByKey =
            BuildIndex();

        private static System.Collections.Generic.Dictionary<string, Speaker> BuildIndex()
        {
            var map = new System.Collections.Generic.Dictionary<string, Speaker>(
                System.StringComparer.OrdinalIgnoreCase);
            foreach (var s in All) map[s.Key] = s;
            return map;
        }

        /// <summary>This character as a speaker, or null for one the game never
        /// gave a voice -- a bust in a crowd, or a pack's own character.</summary>
        public static Speaker For(string characterKey)
        {
            Speaker found;
            return !string.IsNullOrEmpty(characterKey)
                && ByKey.TryGetValue(characterKey, out found) ? found : null;
        }

        /// <summary>Whether the game gave this character a voice.</summary>
        public static bool Has(string characterKey)
        {
            return For(characterKey) != null;
        }
    }
}
