using System.Collections.Generic;

namespace SMSModForge.Documentation;

/// <summary>One bullet: an optional bold UI label, then what it does.</summary>
public sealed class DocBullet
{
    public string Term { get; }
    public string Text { get; }

    public DocBullet(string term, string text) { Term = term; Text = text; }
    public DocBullet(string text) : this("", text) { }

    /// <summary>Separator drawn between label and body — nothing when the
    /// bullet is a plain sentence with no label.</summary>
    public string Dash => Term.Length == 0 ? "" : " — ";
}

/// <summary>A group of bullets under an optional heading. Headings mirror the
/// GroupBox captions on screen, so the docs read in the same order as the UI.</summary>
public sealed class DocSection
{
    public string Heading { get; }
    public IReadOnlyList<DocBullet> Bullets { get; }
    public bool HasHeading => Heading.Length > 0;

    public DocSection(string heading, params DocBullet[] bullets)
    { Heading = heading; Bullets = bullets; }
}

/// <summary>One expander in the Documentation list.</summary>
public sealed class DocTopic
{
    public string Title { get; }
    public string Summary { get; }
    public IReadOnlyList<DocSection> Sections { get; }

    public DocTopic(string title, string summary, params DocSection[] sections)
    { Title = title; Summary = summary; Sections = sections; }

    /// <summary>Whether the topic opens already expanded. False for the
    /// catalog itself; set on the copies <see cref="DocSearch"/> returns, so a
    /// search result does not have to be opened by hand to be read.</summary>
    public bool StartExpanded { get; init; }
}

/// <summary>A titled run of topics (Concepts, The workspace, Tabs, …).</summary>
public sealed class DocPart
{
    public string Name { get; }
    public IReadOnlyList<DocTopic> Topics { get; }

    public DocPart(string name, params DocTopic[] topics) { Name = name; Topics = topics; }
}

/// <summary>
/// The end-user reference shown in the ModForge tab's Documentation section.
/// <para/>
/// Content lives here rather than in MainWindow.xaml so the prose can be read
/// and reviewed as prose — a few hundred bullets inside XML attributes is
/// unreadable, and that file is large enough already. The view binds
/// <see cref="Parts"/> and renders it generically, so adding a topic is a data
/// change with no XAML edit.
/// <para/>
/// House style: one bullet per control, in on-screen order; the exact UI label
/// as the term; a second sentence only when it earns one. No internals — if a
/// sentence would only make sense to someone who had read the source, it does
/// not belong here.
/// </summary>
public static class DocTopics
{
    public static IReadOnlyList<DocPart> Parts { get; } = new[]
    {
        new DocPart("Start here",

            new DocTopic("What a mod pack is",
                "The whole idea, before any of the detail.",
                new DocSection("",
                    new DocBullet("A pack is one folder. Everything you author ends up in a single file inside it called modpack.json, and the images and audio sit beside that file."),
                    new DocBullet("You never edit modpack.json by hand. The editor writes it, and the tabs across the top are the things it can hold."),
                    new DocBullet("Export turns the folder into one .smspack file. That is what you hand to players, and the only thing the game reads."),
                    new DocBullet("The game does not know the editor exists. It reads your pack through the SMSModForge plugin, which is what actually builds your characters, rooms and conversations inside the running game.")),
                new DocSection("Worth knowing",
                    new DocBullet("A pack adds to the game rather than replacing it. Your places sit alongside the game's own, and a vanilla extension adds to a room the game already has instead of swapping it out."),
                    new DocBullet("Nothing you do in the editor touches your game installation until you export and copy the pack in yourself."))),

            new DocTopic("The order to work in",
                "Which tabs depend on which, so you are not blocked halfway through.",
                new DocSection("",
                    new DocBullet("First", "File then New pack, and Save straight away. Previews and file pickers resolve paths against the pack folder, so much of the editor stays empty until that folder exists on disk."),
                    new DocBullet("Who", "Characters, then NPCs. A character can speak; an NPC just stands in a room. Both want their art before anything else can point at them."),
                    new DocBullet("Where", "Places, then Map Buttons. A place is a room. A map button is how a player reaches one."),
                    new DocBullet("What they say", "Dialogues. A dialogue belongs to a level and its lines name characters, so both are worth having first."),
                    new DocBullet("What plays", "Scenes, Music, SFX and Wallpapers. These are things a dialogue or a rule can trigger, so add them before the logic that fires them."),
                    new DocBullet("State and logic", "Variables, then Integration. A variable has to exist before a condition or an action can name it."),
                    new DocBullet("Last", "Validate (F5), fix what it lists, then Export.")),
                new DocSection("Worth knowing",
                    new DocBullet("An NPC is defined once on the NPCs tab and then placed into a room from the Places tab, so you will come back to Places after making one."),
                    new DocBullet("Nothing enforces this order. It is simply the order that avoids pointing at things you have not made yet."))),

            new DocTopic("How things point at each other",
                "The four ways one part of a pack names another, and where each turns up.",
                new DocSection("",
                    new DocBullet("By runtime name", "Most references are just the other item's runtime name: a dialogue node names a character, a placement names an NPC, a condition names a variable."),
                    new DocBullet("By place token", "Anywhere a field means a room or a level. vanilla:Name is one of the game's own levels; place:Key and self:Key are both a place your pack defines, spelt place: where the field means which level this belongs to and self: where it means where to go; pack:PackId.Key reaches a place in somebody else's pack."),
                    new DocBullet("By hierarchy path", "Anywhere a field means one particular object inside a room, written with arrows, as in NPCs > Shower > Anis > Naked. A path rather than a bare name because names repeat all over a level, and a bare name would find whichever copy the game happened to reach first."),
                    new DocBullet("By file path", "Art and audio, relative to the pack folder.")),
                new DocSection("Worth knowing",
                    new DocBullet("You pick all of these from dropdowns, but the boxes are editable and show the raw token once you have picked. That is expected: the token is what gets written to the pack, and the friendly name only lives in the list."),
                    new DocBullet("Validate flags a token that does not resolve and suggests near matches, which is usually enough to spot a typo or something renamed underneath it."),
                    new DocBullet("Renaming an item leaves everything pointing at its old name. Variables are the one exception, where the rename is applied everywhere at once."))),

            new DocTopic("Putting values into text",
                "Showing a variable inside a line, a label, or another value.",
                new DocSection("",
                    new DocBullet("[PV:name]", "In dialogue text and in button labels, replaced with one of your pack's variables. On a button label it keeps up as the value changes; in a dialogue line it is resolved as the dialogue is built."),
                    new DocBullet("{Name}", "The game's own syntax for the game's own variables, resolved as each line is displayed. {PCName} is the player's name. Use this rather than a pack variable for anything the game already tracks."),
                    new DocBullet("$name", "In an action or condition value box, stands for that variable's current value instead of a fixed one."),
                    new DocBullet("$$", "A literal dollar sign, for the rare case you need one."),
                    new DocBullet("{item}", "In an integration rule that repeats over a list, stands for whichever value the rule is running for.")),
                new DocSection("Worth knowing",
                    new DocBullet("The two sets of variables are separate. {Name} cannot see a pack variable, and [PV:name] cannot see one of the game's."),
                    new DocBullet("A condition or action can still read and write the game's own variables — that is the Source toggle on a Variable row. It is only the text token that is one-sided."),
                    new DocBullet("A variable that has never been set reads as empty. That usually means nothing happens, rather than an error."))),

            new DocTopic("When something does not work",
                "The three things to check, in the order worth checking them.",
                new DocSection("",
                    new DocBullet("Validate (F5)", "Every check across the whole pack, listed on this tab. Double-click a row to jump to whatever it is complaining about. Start here: most problems are a missing file or a name that no longer resolves."),
                    new DocBullet("The previews", "They compose your art exactly as the game lays it out, but they do not run the game's logic. Conditions, variables and rules are not evaluated, so anything gated on state is drawn regardless — a preview looking right does not mean the gate works."),
                    new DocBullet("In-game logging", "Flag a dialogue for condition debugging on the Dialogues tab, or a rule for decision logging on the Integration tab, and the game will log why it did or did not fire.")),
                new DocSection("Worth knowing",
                    new DocBullet("A pack that does not appear at all is usually installed wrong rather than broken. The .smspack belongs in BepInEx/plugins/SMSModForge/ModPacks/ inside your game folder."),
                    new DocBullet("An empty preview on a pack you have not saved yet is expected. Previews resolve paths against the pack folder."),
                    new DocBullet("Both logging flags are stored in the pack, so tracking left switched on ships to players as extra logging. Clear them before a release.")))),

        new DocPart("Concepts",

            new DocTopic("Packs and the .smspack",
                "What a pack is made of, and what actually reaches the game.",
                new DocSection("",
                    new DocBullet("Pack folder", "Where you work. It holds modpack.json plus every image and audio file the pack uses, in whatever subfolders suit you."),
                    new DocBullet("modpack.json", "Everything you author in the editor: characters, places, dialogues, variables, rules. Media files sit beside it and are referred to by path."),
                    new DocBullet(".smspack", "The single file the game loads, built by Export. It is a zip with modpack.json at the top and every other file keeping exactly the path it had in the folder."),
                    new DocBullet("Installing", "Drop the .smspack into BepInEx/plugins/SMSModForge/ModPacks/ inside your game folder. See Exporting and installing.")),
                new DocSection("Worth knowing",
                    new DocBullet("Because paths inside the archive match the folder exactly, moving a sprite and re-exporting is all it takes — nothing needs re-pointing."),
                    new DocBullet("A pack owns its whole folder. Export bundles everything inside it, subfolders included, whether the pack refers to it or not — so give a pack a folder of its own rather than saving it into somewhere like your Desktop, which would put every file there into the exported pack."),
                    new DocBullet("Version-control folders, editor clutter and any earlier .smspack sitting in the folder are left out."))),

            new DocTopic("Runtime names and display names",
                "Every item has an identifier the pack uses, and a name you read.",
                new DocSection("",
                    new DocBullet("Runtime name", "The identifier everything else points at. Keep it short, and change it as rarely as you can."),
                    new DocBullet("Display name", "What the editor's lists show. For a character it is also the speaker name players see above the line; everywhere else it is for your eyes only.")),
                new DocSection("Worth knowing",
                    new DocBullet("A dialogue node's Actor field takes a character's runtime name, and the line is then labelled with that character's display name."),
                    new DocBullet("The Edit menu calls the same thing the item's key, when duplicating or renaming."),
                    new DocBullet("Two items of the same kind cannot share a runtime name, and Validate flags duplicates."),
                    new DocBullet("Renaming one leaves anything pointing at it pointing at the old name — variables excepted, where the rename is applied everywhere at once."))),

            new DocTopic("Folders and lists",
                "Grouping items so long lists stay navigable.",
                new DocSection("",
                    new DocBullet("+ Folder", "Make a folder in the current tab's list, then drag items into it."),
                    new DocBullet("Folders are saved with the pack, but the game ignores them entirely. They exist for your benefit while authoring."),
                    new DocBullet("Renaming a folder, or moving items between folders, never changes anything the game does."))),

            new DocTopic("Condition and action lists",
                "The shared editor used everywhere the pack asks when something happens, or what happens next.",
                new DocSection("",
                    new DocBullet("+ Add condition", "Add a requirement. Every condition in a list has to pass, and an empty list always passes."),
                    new DocBullet("+ Add action", "Add something to do when the list is satisfied. Actions run top to bottom."),
                    new DocBullet("+ Add group", "Bundle conditions the way brackets would, for when a flat list of requirements is not enough. A group can ask for all of its conditions or any of them."),
                    new DocBullet("Copy all / Paste / Overwrite", "Move a whole list somewhere else. Paste adds to what is already there; Overwrite replaces it.")),
                new DocSection("Worth knowing",
                    new DocBullet("The clipboard is shared across dialogues, rules and place hooks, so a set of conditions worked out once can be reused wherever it fits."),
                    new DocBullet("A dialogue's start conditions keep their level gate through an Overwrite, since that is what decides where the dialogue belongs."))),

            new DocTopic("The mask painter",
                "The window behind every Edit Mask button, for painting where an effect applies.",
                new DocSection("",
                    new DocBullet("A mask is not artwork — it records how much of an effect each part of a sprite gets. You paint it over the real art, so you can see what you are marking."),
                    new DocBullet("Layers", "A character or NPC mask has three, painted separately: Bounce, Wave and Noise. A place mask has one, called Intensity, and the other two panels are hidden because that effect reads nothing else."),
                    new DocBullet("Reference (locked)", "The real art underneath, there to trace against and never edited."),
                    new DocBullet("Tools", "A brush and an eraser, with Size, Hardness and Opacity. Zoom changes how close you are working, not what is painted."),
                    new DocBullet("Cap at opacity", "Makes the opacity slider a ceiling instead of a strength: strokes build up towards it and stop, and anywhere already stronger is left alone. The way to even out a patch without flattening it."),
                    new DocBullet("Clear active channel / Fill active channel", "Empty or completely fill the layer you are on — the quickest way to start from none or all of an effect."),
                    new DocBullet("Save (Ctrl+S) / Close", "Write the mask back to its file, or leave it as it was.")),
                new DocSection("Which layer moves what",
                    new DocBullet("Bounce", "Up and down. Speed sets how fast the cycle runs, Strength how far the pixels travel."),
                    new DocBullet("Wave", "Side to side, as a ripple running down the sprite. Wave frequency decides how tight that ripple is — low sways, high ripples. Speed and Strength are shared with Bounce."),
                    new DocBullet("Noise", "A drifting, irregular wobble in both directions at once. Its own three settings: Noise scale is how fine the grain is, Noise speed how fast it drifts, Noise strength how much shows through."),
                    new DocBullet("Intensity", "On a place mask there is only the one layer, and it scales that place's own movement."),
                    new DocBullet("The six settings sit under Jiggle on the Characters tab and on the NPCs tab, with the same names in both places.")),
                new DocSection("Hotkeys",
                    new DocBullet("B / E", "Brush or eraser."),
                    new DocBullet("1 / 2 / 3", "Switch to Bounce, Wave or Noise. Only 1 does anything on a place mask."),
                    new DocBullet("R / G", "Show or hide the Bounce or Wave layer. Noise has a toggle button of its own, but no key."),
                    new DocBullet("D", "Show or hide the reference art underneath."),
                    new DocBullet("[ / ]", "Smaller or larger brush."),
                    new DocBullet(", / .", "Less or more opacity. Hold Shift for bigger steps."),
                    new DocBullet("C / F", "Clear or fill the layer you are on."),
                    new DocBullet("Ctrl+Z / Ctrl+Y", "Undo or redo."),
                    new DocBullet("Ctrl+S", "Save the mask to its file."),
                    new DocBullet("Wheel-drag / Home", "Pan the canvas, or reset zoom and pan.")),
                new DocSection("Worth knowing",
                    new DocBullet("In the file itself a character mask keeps Bounce, Wave and Noise in the red, green and blue channels with alpha scaling all three, and a place mask keeps its one layer in alpha alone. That only matters if you ever paint a mask in another program — here it is handled for you."))),

            new DocTopic("Previews",
                "What the preview panes show, and what only ever happens in game.",
                new DocSection("",
                    new DocBullet("Previews compose your art the way the game lays it out — at the game's own resolution, with the interface frame and navigator strip in place — so positions and sizes are true to what players will see."),
                    new DocBullet("They do not run the game's logic. Conditions, variables and integration rules are not evaluated, so anything gated on state is drawn regardless."),
                    new DocBullet("Previews resolve image paths against the pack folder, so they stay empty until the pack has been saved."),
                    new DocBullet("Preview quality on the Options menu trades smoothness against processor load.")))),

        new DocPart("The workspace",

            new DocTopic("File menu",
                "Creating, opening, saving and exporting packs.",
                new DocSection("",
                    new DocBullet("New pack", "Start an empty pack. Save it before doing anything else — previews and file pickers resolve paths against the pack folder, so they stay empty until it exists on disk."),
                    new DocBullet("Open pack…", "Open a pack folder you have already saved."),
                    new DocBullet("Recent files", "Reopen one of the packs you worked on most recently."),
                    new DocBullet("Save", "Write the pack folder to disk. With Confirm changes on save switched on, you get a list of everything the save will change first."),
                    new DocBullet("Save as…", "Write the pack to a new folder and carry on working in that copy."),
                    new DocBullet("Export pack", "Save, then bundle the folder into the single .smspack file the game loads, reusing wherever you last exported this pack. Asks the first time."),
                    new DocBullet("Export pack as…", "The same, but always asks where to put it, and the location you pick becomes the one-click Export target from then on."),
                    new DocBullet("Validate", "Re-run every check and refresh the Issues list on the ModForge tab.")),
                new DocSection("Worth knowing",
                    new DocBullet("Both Export items stay disabled until the pack has been saved at least once, because the exporter bundles what is on disk rather than what is on screen."),
                    new DocBullet("The export location is remembered by the editor rather than stored in the pack, so it does not travel when you share the pack folder."))),

            new DocTopic("Edit menu",
                "Acts on the selected item in the current tab's list.",
                new DocSection("",
                    new DocBullet("Duplicate item", "Copy the selected item into the same list with a fresh runtime name."),
                    new DocBullet("Copy item", "Copy the selected item. You can paste it into any pack you open in the same editor session."),
                    new DocBullet("Paste item", "Paste a copied item into the current tab, as long as the types match."),
                    new DocBullet("Rename item…", "Change the selected item's runtime name, which the menu calls its key."),
                    new DocBullet("Delete item", "Remove the selected item from the pack.")),
                new DocSection("Worth knowing",
                    new DocBullet("Renaming a variable is a true rename: every reference to it is rewritten at the same time, including $name uses and [PV:name] tokens in dialogue text and button labels."),
                    new DocBullet("Renaming anything else changes the name only. Anything pointing at the old one keeps pointing at it, so run Validate afterwards to catch what broke."),
                    new DocBullet("Each shortcut also works with the list focused, without opening the menu."),
                    new DocBullet("The ModForge tab has no item list, so these do nothing while you are on it."))),

            new DocTopic("Options menu",
                "Editor preferences. All of them are remembered between sessions.",
                new DocSection("",
                    new DocBullet("Confirm changes on save", "List everything a save will change, and ask before writing. Ticking Don't ask again in that dialog switches this off; turn it back on here to get the prompt back."),
                    new DocBullet("Spell-check node text", "Underline misspellings in a node's Text field and down the node list, using the same US-English checker Windows uses elsewhere. Right-click a squiggle for suggestions, to ignore the word for this session, or to add it to your Windows dictionary. Switching it off also makes very long node lists lighter to scroll."),
                    new DocBullet("Add pack names to Windows dictionary…", "Add every character, place and NPC name the pack invents to your Windows dictionary at once, so they stop being flagged. Shows you the list before adding anything."),
                    new DocBullet("Preview quality", "Trade preview smoothness against processor load: Ultra (60 fps, anti-aliased), High (30 fps, anti-aliased), Medium (30 fps, no anti-aliasing), Low (20 fps, no anti-aliasing).")),
                new DocSection("Worth knowing",
                    new DocBullet("The Windows dictionary is shared with the rest of your system, so words added here also stop being flagged in other apps that use it."))),

            new DocTopic("Themes",
                "Recolours the editor. Your choice is remembered between sessions.",
                new DocSection("",
                    new DocBullet("Light themes", "Light, Slate, Forest, Plum, Ocean, Sandstone and Rose."),
                    new DocBullet("Dark themes", "Dark, Midnight and Carbon."),
                    new DocBullet("Themes change the editor only. They have no effect on the pack, or on anything in the game."))),

            new DocTopic("The ModForge tab",
                "The landing page: how to learn the editor, what is wrong with the pack, and what you have flagged for debugging.",
                new DocSection("Learning",
                    new DocBullet("Getting started", "The four steps a pack goes through, from New pack to Export. Worth reading once."),
                    new DocBullet("Guided tutorials", "Seven walkthroughs that build a real pack a control at a time — a character, a room, a conversation, a jiggle mask, NPCs, variables and rules. Each one lights up exactly the controls its instructions name, and most steps wait until you have actually done the thing before moving on."),
                    new DocBullet("Documentation", "This reference. The search box matches titles, headings and the text of every bullet, and results open already expanded."),
                    new DocBullet("The tutorials keep what they make. Each one carries on in the pack the last one left, so they build one pack between them rather than seven throwaways."),
                    new DocBullet("A finished tutorial is ticked and its button becomes Again. That is remembered by the editor rather than stored in the pack, so it follows you and not the pack.")),
                new DocSection("Issues",
                    new DocBullet("Validate (F5)", "Re-run every check across the whole pack."),
                    new DocBullet("Issue list", "One row per problem, showing how serious it is, where it is, and what is wrong. Double-click a row to jump straight to the item."),
                    new DocBullet("Error", "Something that will not work in game, such as a missing file or a reference to something that does not exist."),
                    new DocBullet("Warning", "Something suspicious that may still work, and is usually a mistake."),
                    new DocBullet("Info", "A note worth reading; nothing is broken."),
                    new DocBullet("The count also sits in the status bar at the bottom of the window, so you can see it from any tab.")),
                new DocSection("Debug tracking",
                    new DocBullet("Tracked for condition debugging", "Dialogues you have flagged on the Dialogues tab. While flagged, the game logs why the dialogue did or did not start."),
                    new DocBullet("Rules logging decisions", "Integration rules you have flagged on the Integration tab. While flagged, the game logs which branch each rule picked, whenever that choice changes."),
                    new DocBullet("Untrack", "Stop tracking that one item."),
                    new DocBullet("Untrack all", "Clear the whole list."),
                    new DocBullet("Both lists are stored in the pack, so tracking left switched on ships to players as extra logging. Clear them before a release."))),

            new DocTopic("Keyboard shortcuts",
                "Everything with a shortcut, in one place.",
                new DocSection("Pack",
                    new DocBullet("Ctrl+N", "New pack."),
                    new DocBullet("Ctrl+O", "Open pack."),
                    new DocBullet("Ctrl+S", "Save."),
                    new DocBullet("Ctrl+Shift+S", "Save as."),
                    new DocBullet("Ctrl+E", "Export pack."),
                    new DocBullet("Ctrl+Shift+E", "Export pack as."),
                    new DocBullet("F5", "Validate.")),
                new DocSection("Selected item",
                    new DocBullet("Ctrl+D", "Duplicate."),
                    new DocBullet("Ctrl+C", "Copy."),
                    new DocBullet("Ctrl+V", "Paste."),
                    new DocBullet("F2", "Rename."),
                    new DocBullet("Del", "Delete.")))),

        new DocPart("The tabs",

            new DocTopic("Characters",
                "Who speaks, what they look like, and how their voice sounds.",
                new DocSection("Adding one",
                    new DocBullet("+ Character", "A character this pack draws the bust for."),
                    new DocBullet("+ Vanilla", "A character who borrows one of the game's own busts. No art needed — its outfits are vanilla bust names, one per bust it can appear as, and its name colour belongs to the game."),
                    new DocBullet("+ Voice", "A speaking part with no bust at all. Lines, name colour and voice all work; nothing is drawn."),
                    new DocBullet("− Character", "Delete the character and all of its outfits.")),
                new DocSection("The player",
                    new DocBullet("Every pack has a player character it did not create, and it is already in the list. A dialogue in any mod that addresses you reaches this same character, so its name, colour, key and source are fixed and it cannot be renamed or deleted."),
                    new DocBullet("Its typing voice is still yours to set."),
                    new DocBullet("Use it as the speaker on any line the player says.")),
                new DocSection("Identity",
                    new DocBullet("Character name", "What the player reads on a speech line. The only name you have to write — the internal ones follow from it."),
                    new DocBullet("Name colour", "Tints the speaker name. Leave it blank for the default, type a hex value, or use Pick to choose from a colour wheel."),
                    new DocBullet("Bust source", "Where this character's art comes from: drawn by the pack, borrowed from the game, or none at all."),
                    new DocBullet("Default outfit", "Which bust the character appears in before any dialogue changes it."),
                    new DocBullet("Dialogue key", "What a dialogue node names as its speaker."),
                    new DocBullet("GameObject", "The object the bust is built under in game.")),
                new DocSection("Outfits",
                    new DocBullet("An outfit is one complete bust. A character can change outfit between nodes of the same dialogue, so outfits cover costume changes and states as well as clothes."),
                    new DocBullet("+ Outfit / − Outfit", "Add or delete an outfit on the selected character."),
                    new DocBullet("Outfit name", "What dialogue lines and actions refer to this outfit by.")),
                new DocSection("Voice (typewriter blip)",
                    new DocBullet("Enable typewriter voice", "When off, this character's lines type out silently."),
                    new DocBullet("Template", "Male and Female fill in the usual values; Custom leaves them to you."),
                    new DocBullet("Frequency", "How often the blip fires as the text types."),
                    new DocBullet("Pitch min / Pitch max", "The range each blip's pitch is drawn from, so a voice does not sound identical line to line.")),
                new DocSection("Speech expressions",
                    new DocBullet("+ Add expression", "Map a key you will use on a node to one of the expression children on the bust, so a line can call for Happy without naming the artwork.")),
                new DocSection("Sprites",
                    new DocBullet("Base", "The bust itself. Paths are relative to the pack folder."),
                    new DocBullet("Mask", "Decides where the jiggle effect applies and how strongly. Edit Mask opens a painter for it."),
                    new DocBullet("Has Blink frame", "Untick for a character with no blink art. This is how you say a character does not blink — leaving the path empty while it stays ticked makes the runtime read the outfit as broken and skip the whole bust, so the character never appears at all."),
                    new DocBullet("Blink", "The eyes-closed overlay, when the box above is ticked."),
                    new DocBullet("Has Mouth frames / Mouth prefix", "Turn on when the bust has numbered mouth frames, and give the prefix they share, so the mouth animates while the line types."),
                    new DocBullet("Has Expressions / Expr. prefix", "The same for expression artwork.")),
                new DocSection("Jiggle",
                    new DocBullet("These say how the bust moves; the mask says where. Nothing here does anything to a part of the sprite the mask leaves black."),
                    new DocBullet("Speed / Strength", "How fast the cycle runs and how far the pixels travel. Both drive the Bounce and Wave layers of the mask."),
                    new DocBullet("Wave frequency", "How many waves fit down the sprite — low sways, high ripples. The Wave layer only."),
                    new DocBullet("Noise scale / speed / strength", "How fine the irregular drift is, how fast it moves and how much shows through. The Noise layer only, and what keeps the motion from ticking like a metronome."),
                    new DocBullet("Tint (hex)", "Multiplies the bust's colour. Almost always left white."),
                    new DocBullet("Pixel Snap", "Rounds movement to whole pixels, matching the game's own look.")),
                new DocSection("Particles",
                    new DocBullet("Wet particle active on spawn", "Start the wet effect already running. Normally only for swimwear or wet variants.")),
                new DocSection("Preview",
                    new DocBullet("Mouth frame, Expression", "Show the bust in one particular frame or expression."),
                    new DocBullet("Yapping, Blinking, Breathing", "Animate the preview so you can judge the effect rather than a still."),
                    new DocBullet("Depth", "How far the bust bobs in the preview. Preview only — match it to the game by eye."))),

            new DocTopic("NPCs",
                "Standing figures for populating rooms. They are defined here and placed from the Places tab.",
                new DocSection("The list",
                    new DocBullet("+ NPC", "Add an NPC definition."),
                    new DocBullet("+ Folder / Rename / − Remove", "Organise the list. Removing a folder moves its contents up rather than deleting them."),
                    new DocBullet("Ctrl+click and Shift+click select several items, so you can drag a group into a folder at once.")),
                new DocSection("Identity",
                    new DocBullet("Display name", "What you read in the list."),
                    new DocBullet("Runtime name", "What a placement on the Places tab refers to this NPC by.")),
                new DocSection("Sprite and mask",
                    new DocBullet("Pose sprite", "The artwork. Any resolution — it is read at its own size."),
                    new DocBullet("Jiggle mask", "Where the jiggle applies, painted the same way as a bust mask. Edit Mask opens the painter."),
                    new DocBullet("Default sorting order", "How far forward the NPC draws. The game's own reference NPCs sit just behind a room's props.")),
                new DocSection("Jiggle",
                    new DocBullet("The same six settings as a character, with the same names and the same meanings — see Characters, or The mask painter for which layer each one drives."),
                    new DocBullet("Speed / Strength", "How fast the cycle runs and how far the pixels travel. Both drive the Bounce and Wave layers."),
                    new DocBullet("Wave frequency", "How tight the side-to-side ripple is. The Wave layer only."),
                    new DocBullet("Noise scale / speed / strength", "The irregular drift. The Noise layer only."),
                    new DocBullet("Tint, Pixel snap", "Colour multiplier, and whether movement rounds to whole pixels.")),
                new DocSection("Blink",
                    new DocBullet("Blink sprite", "Eyes-closed artwork. Leave blank for no blinking."),
                    new DocBullet("Open wait min/max", "How long the eyes stay open between blinks, drawn from this range."),
                    new DocBullet("Closed hold", "How long a blink lasts.")),
                new DocSection("Reflection",
                    new DocBullet("Enabled", "Draw a mirrored copy beneath the pose, for wet streets and polished floors."),
                    new DocBullet("Alpha", "How visible it is. The game's own reflections read as a faint wash rather than a second character."),
                    new DocBullet("Tint", "A reflection takes the colour of whatever it lies on; the default is the muted shade the game uses for street reflections."),
                    new DocBullet("Y offset, Sorting order", "Where it sits and how far forward it draws.")),
                new DocSection("Shadow",
                    new DocBullet("Enabled", "Draw a simple shadow under the NPC, shaped by the pose's own transform."),
                    new DocBullet("Colour, Sorting order", "Its shade and how far forward it draws.")),
                new DocSection("Wet particles",
                    new DocBullet("Enabled / Start active", "Whether the NPC has the wet effect at all, and whether it is already running when the room loads.")),
                new DocSection("Preview",
                    new DocBullet("Shows the pose with jiggle, shadow and blink running together, so the parts can be judged as a whole."))),

            new DocTopic("Places",
                "Rooms and locations — the ones your pack builds, and additions to the ones the game already has.",
                new DocSection("Two lists",
                    new DocBullet("Your places", "Locations your pack builds from its own art."),
                    new DocBullet("Vanilla extensions", "A place that already exists in the game, which your pack adds to — a button leading somewhere new, or objects layered on top. The game's own objects stay as they are unless you change them deliberately.")),
                new DocSection("Identity",
                    new DocBullet("Source place", "On a vanilla extension only: which of the game's own places this extension attaches to. Everything you add below then appears when the player is there."),
                    new DocBullet("Display name (button)", "The name players read on the navigator button that leads here."),
                    new DocBullet("Runtime name", "What conditions, actions and navigator targets refer to this place by."),
                    new DocBullet("Internal GO name", "The object the level is built as in game.")),
                new DocSection("Level art",
                    new DocBullet("Back sprite", "The layer drawn behind, at sorting order −12. Usually the room itself, or the distance seen past it."),
                    new DocBullet("Front sprite", "The layer drawn in front, at −10. Anything that should sit over the back one — an object standing in the room, or a foreground the player looks past. Often left empty."),
                    new DocBullet("Sorting order", "How far forward each of the two draws. Higher is nearer the viewer, which is why the front layer's −10 sits over the back layer's −12."),
                    new DocBullet("Back mask / Front mask", "Optional masks shaping how each piece of artwork is drawn. Edit opens a painter for them."),
                    new DocBullet("A note on the names", "The pack file calls these two layers baseSprite and secondarySprite — the game's own naming, and the opposite way round from what you would expect, since baseSprite is the front one. The editor says back and front instead, and each field's tooltip names the key it writes.")),
                new DocSection("Behaviour",
                    new DocBullet("Parallax — front", "How far the front layer slides as the cursor moves. Every place in the game uses the same value, so start there."),
                    new DocBullet("Parallax — back", "The back layer's own drift. Setting it away from the front is what creates depth; Same as front switches that off."),
                    new DocBullet("Reverse front / Reverse back", "Drift with the cursor instead of against it. Rarely wanted, and the game itself only does it once."),
                    new DocBullet("Keep beach audio / Keep seagulls", "Carry the ocean ambience and seagull particles over from the beach this place is built on."),
                    new DocBullet("Weather", "Whether the game's rain and snow run here. None is no weather at all, Inside is the muted indoor version seen through windows, Outside is the full effect.")),
                new DocSection("Contents",
                    new DocBullet("+ Add navigator button", "Add a button to this place's strip, leading somewhere else. Twelve at most per place — the count beside the button says how many you have used, and it stops offering once you are at the limit."),
                    new DocBullet("+ Add GameObject", "Add an object to the room — art, a prop, a container for other objects."),
                    new DocBullet("+ Add NPC", "Place one of your NPCs into the room. To hang it under a particular container instead, use that container's own NPCs section."),
                    new DocBullet("Fill from vanilla hierarchy", "On a vanilla extension, add an entry for every object the game's version of this place already has, each with its real position. Existing entries are left alone, so it is safe to run again later to pick up anything new.")),
                new DocSection("On enter / On exit",
                    new DocBullet("+ Add action group", "Actions that run once when the player arrives at this place, or once when they leave.")),
                new DocSection("Preview",
                    new DocBullet("Fade under an inactive parent", "The game draws nothing beneath a switched-off parent, so those objects are faded here to show the room as it will really load. Untick while positioning them."),
                    new DocBullet("Fade objects that start inactive", "The same for objects parked for a rule to switch on later."),
                    new DocBullet("Preview parallax", "Drift the scene with the cursor as the game does. Viewing only — leave it off while positioning."),
                    new DocBullet("Apply shaders", "Run the real jiggle pass over NPCs that have a mask, using this pack's own numbers. Costs a little processor time, so leave it off while positioning."))),

            new DocTopic("Map Buttons",
                "Entries on the world map, so players can reach your places.",
                new DocSection("",
                    new DocBullet("+ Map button", "Add a button to the world map."),
                    new DocBullet("Target place", "Where the button takes the player."),
                    new DocBullet("District", "Which of the world map's radial menus the button appears under: Seaside, The Line, Neon Row, Shopside or Foundry."),
                    new DocBullet("Label", "The button's text. It accepts [PV:name] tokens, so a dialogue or rule can rename the button while the game is running."),
                    new DocBullet("Music (optional)", "A track to switch to when the button is used."),
                    new DocBullet("Conditions", "Gate the button so it only appears once the player has earned it. Leave the list empty and it is always there. See Condition and action lists."),
                    new DocBullet("− Remove selected", "Delete the selected map button."))),

            new DocTopic("Dialogues",
                "Conversations: when they start, and what happens line by line.",
                new DocSection("Identity",
                    new DocBullet("Display name", "What you read in the list."),
                    new DocBullet("Runtime name", "What jumps, logs and other packs refer to this dialogue by."),
                    new DocBullet("Priority", "When several dialogues become eligible at the same moment, the highest priority starts first.")),
                new DocSection("How it starts",
                    new DocBullet("Start conditions", "What has to be true for the dialogue to play. See Condition and action lists."),
                    new DocBullet("Prioritize this dialogue over vanilla", "Hold back the room's own entry conversation while yours is eligible, so the two do not compete. Only offered in rooms that have one."),
                    new DocBullet("Also leave on the Talk button (replayable)", "Play on arrival as usual, and stay on the Talk button so the player can hear it again for as long as its conditions hold. Without this, a dialogue plays once and is gone until its conditions fail and pass again."),
                    new DocBullet("Wait for Talk button (no auto-play)", "Do not play on arrival at all — park behind the Talk button and let the player start it. Unavailable while the replay option is on, since that one plays on arrival by definition."),
                    new DocBullet("Queue behind active dialogue", "If something else is playing when this becomes eligible, wait and start straight afterwards. Without it, this dialogue misses that moment and waits for the next one."),
                    new DocBullet("Set for condition debugging (F12)", "In game, F12 logs which start conditions passed and failed, with the values behind them. Diagnostic only — it changes nothing about play.")),
                new DocSection("Nodes",
                    new DocBullet("A dialogue is a tree. Play starts at the first root and works down: a node runs, then its children in order, until something exits."),
                    new DocBullet("+ Root", "Add a node at the top level, with no parent."),
                    new DocBullet("+ Child", "Add a child of the selected node, copying everything from it but the text and the tag."),
                    new DocBullet("+ Sibling", "Add a node directly below the selected one under the same parent, copied the same way."),
                    new DocBullet("− Remove", "Delete the selected node. Anything pointing at it is tidied up for you."),
                    new DocBullet("Copy node, and the three Paste options", "Move a node and everything beneath it — below the selection, into it as a child, or out to a new root.")),
                new DocSection("The selected node",
                    new DocBullet("Kind", "Text plays a line. Choice offers the children and lets the player pick one. Random picks one of them itself."),
                    new DocBullet("Actor, Expression, Outfit", "Who is speaking and how they look, from this node onward. Outfit also accepts $variableName, so a node can pick the outfit from a variable."),
                    new DocBullet("Text", "The line itself. [PV:name] tokens are filled in as it displays."),
                    new DocBullet("Tag", "An optional label so another node can jump here."),
                    new DocBullet("Jump", "What happens after this node: carry on into its children, exit the dialogue, or jump to a tag."),
                    new DocBullet("Duration", "UntilInteraction waits for the player; Timeout moves on by itself once the line has finished typing."),
                    new DocBullet("Timeout (s)", "How long the finished line lingers before it advances, in Timeout mode.")),
                new DocSection("Per-node conditions and actions",
                    new DocBullet("Conditions (gate this node)", "Skip the node when they fail. Beneath a Choice, a child that fails is simply not offered to the player."),
                    new DocBullet("Actions on start", "Run as the line begins."),
                    new DocBullet("Actions on finish", "Run as the line ends — the usual home for anything that should not take effect until the player has read it."))),

            new DocTopic("Scenes",
                "Full-screen images shown during a conversation.",
                new DocSection("Identity",
                    new DocBullet("Display name", "What you read in the list."),
                    new DocBullet("Runtime name", "What actions and conditions refer to this scene by.")),
                new DocSection("Scene image",
                    new DocBullet("Sprite path", "The artwork, relative to the pack folder.")),
                new DocSection("Frame",
                    new DocBullet("Vanilla frame", "Use one of the borders that ship with the game."),
                    new DocBullet("Custom frame", "Use your own border instead. Set, it wins over the vanilla one.")),
                new DocSection("Sound",
                    new DocBullet("Mode", "Silent plays nothing. Kiss and Flash play the matching effect as the scene appears. None keeps whatever sound the scene was built from already had — rarely what you want.")),
                new DocSection("Worth knowing",
                    new DocBullet("Scenes are shown and hidden by actions on a dialogue node, so a scene on its own never appears until something calls for it."))),

            new DocTopic("Music",
                "Background tracks your pack adds to the game.",
                new DocSection("Identity",
                    new DocBullet("Display name", "What you read in the list."),
                    new DocBullet("Runtime name", "What a music-switching action refers to this track by.")),
                new DocSection("Audio",
                    new DocBullet("Audio path", "The audio file, relative to the pack folder. OGG, WAV and MP3 all work."),
                    new DocBullet("Loop", "Whether the track repeats. Leave it blank to inherit the game's usual behaviour."),
                    new DocBullet("Volume", "How loud it plays, from 0 to 1. Blank inherits.")),
                new DocSection("Preview",
                    new DocBullet("Play / Stop", "Hear the track at the volume above. It plays once here — looping only happens in game — and the pack has to be saved first."))),

            new DocTopic("SFX",
                "Sound effects, played by an action or by the words in a line.",
                new DocSection("Identity",
                    new DocBullet("Display name", "What you read in the list."),
                    new DocBullet("Runtime name", "What a play-sound action refers to this effect by.")),
                new DocSection("Audio",
                    new DocBullet("Audio path", "The audio file, relative to the pack folder. OGG, WAV and MP3 all work."),
                    new DocBullet("Default volume", "Used whenever something plays this effect without saying how loud."),
                    new DocBullet("Play / Stop", "Hear it at the default volume. Needs the pack saved first.")),
                new DocSection("Auto-trigger patterns",
                    new DocBullet("A comma-separated list of text patterns. When one of them appears in a line, the effect fires on its own — no action needed."),
                    new DocBullet("The convention is a lowercase word between asterisks, like *plap*. One effect can carry several patterns, so different words can share a sound."),
                    new DocBullet("Leave it blank for an effect that should only ever play when an action asks for it.")),
                new DocSection("Variants",
                    new DocBullet("An effect can have several recordings, and one is picked at random each time it plays, so a repeated sound does not become monotonous."),
                    new DocBullet("There is no field for them: put the extra files beside the first one with the same name and _1, _2, _3 on the end. Audio/Plap.ogg picks up Audio/Plap_1.ogg and Audio/Plap_2.ogg by itself."),
                    new DocBullet("Number them without gaps. Counting stops at the first missing number, so _1, _2, _4 quietly loads only the first two."),
                    new DocBullet("The extensions do not have to match, so a WAV variant of an OGG effect is fine."),
                    new DocBullet("Play above previews the first recording only — the random pick happens in game."))),

            new DocTopic("Wallpapers",
                "Images the player can unlock and set as their in-game wallpaper.",
                new DocSection("Identity",
                    new DocBullet("Display name", "What you read in the list."),
                    new DocBullet("Runtime name", "What actions and conditions refer to this wallpaper by.")),
                new DocSection("Image",
                    new DocBullet("Sprite path", "The image, relative to the pack folder. Full screen, so author it at the game's own resolution."),
                    new DocBullet("External path", "An absolute path to an image sitting outside the pack. Useful while moving content across, but it makes the pack dependent on that file being present, so prefer a bundled image. Set both and the bundled one wins.")),
                new DocSection("Unlock conditions",
                    new DocBullet("What the player has to have done for this wallpaper to become available. Leave the list empty and it is available from the start."))),

            new DocTopic("Variables",
                "The pack's own memory: what it keeps track of, and for how long.",
                new DocSection("Definition",
                    new DocBullet("Name", "What conditions, actions and [PV:] tokens refer to it by."),
                    new DocBullet("Type", "Bool for yes-or-no, Int and Float for numbers, String for text, List for an ordered set of values."),
                    new DocBullet("Default value", "What it starts at before anything has set it. A Bool uses a tick box instead."),
                    new DocBullet("+ Add value", "For a List, the entries it starts out holding."),
                    new DocBullet("Persisted", "Save it with the player's game so it survives closing and reopening. Left off, it starts fresh every session — right for anything that only matters within one visit."),
                    new DocBullet("Description", "A note to yourself, shown only in the editor.")),
                new DocSection("Refreshing",
                    new DocBullet("Refresh mode", "Never leaves the variable alone. Daily resets it to its default each in-game day. DailyRandom gives it a fresh random number each day. LevelRandom re-rolls it every time the player enters one particular place."),
                    new DocBullet("Refresh on level", "Which place re-rolls it, for LevelRandom."),
                    new DocBullet("Min value / Max value", "Limits for a number: the game keeps every write inside them. They also set the range the random refresh modes roll within, which is 0 to 100 if you leave them blank.")),
                new DocSection("Worth knowing",
                    new DocBullet("A daily refresh happens when the player sleeps, at the point the new day actually begins."),
                    new DocBullet("See Putting values into text for the ways a value can be used once it is declared."))),

            new DocTopic("Integration",
                "Rules that watch the game and act on their own, outside any conversation.",
                new DocSection("Identity",
                    new DocBullet("Display name", "What you read in the list."),
                    new DocBullet("Runtime name", "What logs refer to this rule by."),
                    new DocBullet("Description", "A note to yourself, shown only in the editor. The best place to record why a rule exists."),
                    new DocBullet("Set for condition debugging", "In game, log what this rule decided — which branch won, which won last time, and whether it fired, plus a breakdown of every condition when nothing passes. Only logged when the decision changes, so it will not flood the console.")),
                new DocSection("When it fires",
                    new DocBullet("OnRisingEdge", "Once, at the moment the conditions start passing. The most common choice."),
                    new DocBullet("OnFallingEdge", "Once, at the moment they stop passing."),
                    new DocBullet("WhilePassing", "Every frame the conditions hold. Use it sparingly — it is for keeping something continuously in step, not for one-off events."),
                    new DocBullet("OnSceneLoad", "Once when the game world loads, if the conditions pass."),
                    new DocBullet("OnDayChange", "Once per in-game day, if the conditions pass.")),
                new DocSection("Conditions, actions and branches",
                    new DocBullet("Conditions", "What has to be true. See Condition and action lists."),
                    new DocBullet("Actions", "What happens when the rule fires."),
                    new DocBullet("+ Add else-if branch", "A fallback tried when the conditions above, and every earlier branch, fail. The first branch that passes supplies the actions. Leave a branch's conditions empty to make it a plain Else."),
                    new DocBullet("Once a rule has branches, an edge-triggered rule fires whenever the winning branch changes — not only when the rule goes from failing to passing. Moving from one branch to another counts.")),
                new DocSection("Repeat for each",
                    new DocBullet("For each value in", "Run the rule once per value: a List variable written as $name, or a comma-separated list typed in. Blank runs it once."),
                    new DocBullet("Placeholder name", "What to write in braces inside the conditions and actions to stand for the current value. It is item by default, so you write {item}."),
                    new DocBullet("Every value gets its own edge tracking, so the repeats behave exactly like the separate rules they replace.")),
                new DocSection("Editing mode",
                    new DocBullet("Code mode", "Swap the pickers for a JSON view of this rule's conditions and actions. The two views round-trip losslessly, so you can move between them freely; a parse error keeps you in code mode until it is fixed.")))),

        new DocPart("Conditions and actions",

            new DocTopic("Conditions",
                "Everything you can ask about the state of the game.",
                new DocSection("Variables",
                    new DocBullet("Variable", "Compare a variable against a value. Source chooses between your pack's own variables and the game's; Comparison offers equals, greater than, greater or equal, less than, less or equal, and exists — which passes once the variable has been given any value at all."),
                    new DocBullet("VariableStartsWith", "Passes when a text variable begins with something. The one the comparisons above cannot express: where a value is compound, like a location built from a room and a spot in it, a prefix answers which room am I in without listing every spot.")),
                new DocSection("Lists",
                    new DocBullet("ListContains", "Passes when a list holds a particular value. Negate it for does not contain, which is how you express not already taken."),
                    new DocBullet("ListCount", "Compare how many entries a list holds against a number. Equals zero is the empty test, and negating that gives has something in it.")),
                new DocSection("Where things are",
                    new DocBullet("LevelActive", "Passes while a particular place is the one on screen."),
                    new DocBullet("GameObjectActive", "Passes while a particular object is switched on.")),
                new DocSection("Chance and time",
                    new DocBullet("DailyChance", "A percentage rolled once per in-game day, which then holds steady for the rest of it. Every use is its own independent gate — two rules at seventy percent are two separate coin flips, not one shared answer."),
                    new DocBullet("Random", "A percentage rolled fresh every time it is checked."),
                    new DocBullet("Timer", "Passes once an interval has gone by since the rule last fired, then starts counting again. Either a fixed wait or a fresh random interval each time.")),
                new DocSection("Other",
                    new DocBullet("Weather", "Raining, snowing, or either of them. Negate it for clear weather."),
                    new DocBullet("AlwaysTrue", "Passes no matter what. Useful while testing something else.")),
                new DocSection("Where each one is offered",
                    new DocBullet("Most conditions are available anywhere a condition can be written."),
                    new DocBullet("Random is offered only where a condition is checked once and then done with — a node's own conditions, and a place's enter and exit hooks. Anywhere that is checked continuously, a fresh roll every frame would flicker rather than decide, so DailyChance is the one to reach for."),
                    new DocBullet("Timer is offered only on integration rules, because it measures from the last time the rule fired and nothing else has a moment like that.")),
                new DocSection("Worth knowing",
                    new DocBullet("Any condition can be negated, which usually saves writing the opposite test."),
                    new DocBullet("See Condition and action lists for grouping them, and Putting values into text for using one variable's value inside another condition."))),

            new DocTopic("Actions",
                "Everything a dialogue node, an integration rule or a place hook can do.",
                new DocSection("Variables and lists",
                    new DocBullet("Variable", "Write to a variable. Operation chooses what kind of write: Set gives it a value, Increment adds to a number, Random from list picks one entry out of a list, and List count writes how many entries a list holds. Source chooses your pack's variables or the game's."),
                    new DocBullet("AddToList", "Append a value to a list."),
                    new DocBullet("RemoveFromList", "Take the first matching value out of a list."),
                    new DocBullet("ClearList", "Empty a list completely.")),
                new DocSection("Actors",
                    new DocBullet("SetSpriteFocus", "Lift the cast's busts above a full-screen scene, or put them back down. It affects everyone in the dialogue, and resets by itself when the dialogue ends."),
                    new DocBullet("LeaveBust", "Play an actor's fade-out and take them off screen.")),
                new DocSection("Objects on screen",
                    new DocBullet("SetGameObjectActive", "Switch an object on or off — a bust, an overlay, a scene, or anything addressed by path."),
                    new DocBullet("SetSprite", "Swap the artwork on whatever the target addresses, and optionally its mask."),
                    new DocBullet("SetComponentProperty", "Reach a component the other actions do not cover. Today that means a CanvasGroup, for showing and hiding a whole interface panel without switching it off."),
                    new DocBullet("FadeSprite", "Fade a piece of artwork to a chosen opacity over a duration."),
                    new DocBullet("MoveGameObject", "Slide an object to a position over a duration, or send it back where it started."),
                    new DocBullet("SpinGameObject", "Start or stop an object rotating at a steady rate.")),
                new DocSection("Places and scenes",
                    new DocBullet("TransitionLevels", "Cross-fade from one place to another, moving the player mid-conversation."),
                    new DocBullet("DeactivateAllScenes", "Hide every scene this pack has shown. Convenient on a closing node, instead of turning each one off by name.")),
                new DocSection("Signals and interface",
                    new DocBullet("EmitSignal", "Send one of the game's own signals by name, which is how you reach effects the pack has no action for."),
                    new DocBullet("EmitSignalDelayed", "The same, after a wait. The dialogue carries on immediately rather than pausing."),
                    new DocBullet("LeaveUiFaded", "Leave the interface faded when this dialogue ends, because something the node opened is now responsible for bringing it back. Only for a panel that is not part of the main interface, which would be hidden along with it.")),
                new DocSection("Sound",
                    new DocBullet("SwitchMusic", "Change the music that is playing."),
                    new DocBullet("PlaySFX", "Play a sound effect. Stack several on one node, each with its own delay, to build a sequence without holding up the line.")),
                new DocSection("Timing and chance",
                    new DocBullet("Wait", "Pause before the next action runs."),
                    new DocBullet("DiceRoll", "Roll once and do exactly one of several things, each with its own percentage. The editor holds you to a total of a hundred.")),
                new DocSection("World",
                    new DocBullet("SetWeather", "Change today's weather to rain, snow or clear, and update what is on screen straight away.")),
                new DocSection("Worth knowing",
                    new DocBullet("Actions run in the order they are listed."),
                    new DocBullet("Anything that targets an object gives you the same picker — see The target picker."))),

            new DocTopic("The target picker",
                "The shared row for saying which object an action should act on.",
                new DocSection("Categories",
                    new DocBullet("Bust", "A character's bust, as it currently stands on screen."),
                    new DocBullet("GameObjects", "Something your pack added to a place. Pick the place first, then the object within it."),
                    new DocBullet("Places", "The place's own artwork rather than anything in it."),
                    new DocBullet("Scene", "One of your scenes, by name."),
                    new DocBullet("Direct Path", "Anything else, named by where it sits in the game — either a plain object name or a full path like 9_MainCanvas/AfterSleepEvents.")),
                new DocSection("The rest of the row",
                    new DocBullet("Target", "What to act on, offered from whatever the category makes available. It also accepts $variableName, so a rule can act on whichever object a variable currently names — useful for hiding whatever was showing without listing every possibility."),
                    new DocBullet("Level", "Which place to look inside, when the category is GameObjects. Naming it matters while moving between places: it makes sure the object found is the one in the place you meant, not a same-named object still standing in the place being left."),
                    new DocBullet("Layer", "Which of a place's two pieces of artwork to act on, when the category is Places — Back or Front, the same words the Places tab uses.")),
                new DocSection("Worth knowing",
                    new DocBullet("Not every action offers every category. Switching something on or off leaves out Places, because activating a whole place is what moving between places is for."),
                    new DocBullet("Objects that start switched off are still found, so an action can turn on something that was never visible."),
                    new DocBullet("A target that resolves to nothing is reported in the game's log rather than stopping anything, so a mistyped name shows up as an action that quietly does nothing.")))),

        new DocPart("Finishing a pack",

            new DocTopic("Validating",
                "Checking the pack before it goes anywhere.",
                new DocSection("",
                    new DocBullet("Validate (F5) checks the whole pack and fills the Issues list on the ModForge tab. Double-click a row to jump to whatever it is complaining about."),
                    new DocBullet("Errors are things that will not work: a missing file, a required name left blank, a reference to something that no longer exists, two items sharing a key."),
                    new DocBullet("Warnings are things that will run but are probably not what you meant — a default value that does not parse as its type, a character set to borrow a bust without one chosen, two placements landing on the same spot."),
                    new DocBullet("References to places the game ships with are checked against the version the editor knows, so a name that changed between game versions is caught here rather than in play.")),
                new DocSection("Worth knowing",
                    new DocBullet("Validate runs against what is on screen. Save before exporting, since the exporter bundles what is on disk."),
                    new DocBullet("Clear any debug tracking before a release — see The ModForge tab."))),

            new DocTopic("Exporting and installing",
                "Getting the pack into the game.",
                new DocSection("",
                    new DocBullet("Export pack (Ctrl+E)", "Saves, then bundles the pack folder into a single .smspack. The first export asks where; after that the same place is reused."),
                    new DocBullet("Export pack as… (Ctrl+Shift+E)", "Always asks, and the place you choose becomes the new one-click target."),
                    new DocBullet("Installing", "Put the .smspack in BepInEx/plugins/SMSModForge/ModPacks/ inside the game folder. Exporting straight there means testing a change is export, then restart the game."),
                    new DocBullet("Game version", "Each save records which version of the game the pack was built against, and the editor shows that version in its title bar. It travels with the pack, so a pack built for one version can be recognised when the game moves on.")),
                new DocSection("Worth knowing",
                    new DocBullet("Export is unavailable until the pack has been saved at least once."),
                    new DocBullet("See Packs and the .smspack for what ends up inside the file.")))),
    };
}
