using System.Collections.Generic;
using SMSModForge.Localization;

namespace SMSModForge.Documentation;

// Every text here is a key into the English file, read when it is shown rather
// than when the catalogue is built: the catalogue is built once, the first time
// anything looks at it, and whatever language was current then would stick.

/// <summary>One bullet: an optional bold UI label, then what it does.</summary>
public sealed class DocBullet
{
    public string TermKey { get; }
    public string TextKey { get; }

    public string Term => Doc.Text(TermKey);
    public string Text => Doc.Text(TextKey);

    public DocBullet(string termKey, string textKey) { TermKey = termKey; TextKey = textKey; }
    public DocBullet(string textKey) : this("", textKey) { }

    /// <summary>Separator drawn between label and body — nothing when the
    /// bullet is a plain sentence with no label.</summary>
    public string Dash => TermKey.Length == 0 ? "" : " — ";
}

/// <summary>A group of bullets under an optional heading. Headings mirror the
/// GroupBox captions on screen, so the docs read in the same order as the UI.</summary>
public sealed class DocSection
{
    public string HeadingKey { get; }
    public string Heading => Doc.Text(HeadingKey);
    public IReadOnlyList<DocBullet> Bullets { get; }
    public bool HasHeading => HeadingKey.Length > 0;

    public DocSection(string headingKey, params DocBullet[] bullets)
    { HeadingKey = headingKey; Bullets = bullets; }
}

/// <summary>One expander in the Documentation list.</summary>
public sealed class DocTopic
{
    public string TitleKey { get; }
    public string SummaryKey { get; }
    public string Title => Doc.Text(TitleKey);
    public string Summary => Doc.Text(SummaryKey);
    public IReadOnlyList<DocSection> Sections { get; }

    public DocTopic(string titleKey, string summaryKey, params DocSection[] sections)
    { TitleKey = titleKey; SummaryKey = summaryKey; Sections = sections; }

    /// <summary>Whether the topic opens already expanded. False for the
    /// catalog itself; set on the copies <see cref="DocSearch"/> returns, so a
    /// search result does not have to be opened by hand to be read.</summary>
    public bool StartExpanded { get; init; }
}

/// <summary>A titled run of topics (Concepts, The workspace, Tabs, …).</summary>
public sealed class DocPart
{
    public string NameKey { get; }
    public string Name => Doc.Text(NameKey);
    public IReadOnlyList<DocTopic> Topics { get; }

    public DocPart(string nameKey, params DocTopic[] topics) { NameKey = nameKey; Topics = topics; }
}

internal static class Doc
{
    /// <summary>An empty key is an empty text: a section with no heading, a
    /// bullet with no label.</summary>
    public static string Text(string key) => Loc.Optional(key);
}

/// <summary>
/// The end-user reference shown in the ModForge tab's Documentation section.
/// <para/>
/// Content lives here rather than in MainWindow.xaml so the prose can be read
/// and reviewed as prose — a few hundred bullets inside XML attributes is
/// unreadable, and that file is large enough already. The view binds
/// <see cref="Parts"/> and renders it generically, so adding a topic is a data
/// change with no XAML edit.
/// <para/>
/// House style: one bullet per control, in on-screen order; the exact UI label
/// as the term; a second sentence only when it earns one. No internals — if a
/// sentence would only make sense to someone who had read the source, it does
/// not belong here.
/// </summary>
public static class DocTopics
{
    public static IReadOnlyList<DocPart> Parts { get; } = new[]
    {
        new DocPart("docs.part.startHere",

            new DocTopic("docs.modPack.title",
                "docs.modPack.summary",
                new DocSection("",
                    new DocBullet("docs.modPack.packOneFolderEverything"),
                    new DocBullet("docs.modPack.neverEditModpackJson"),
                    new DocBullet("docs.modPack.exportTurnsFolderInto"),
                    new DocBullet("docs.modPack.gameDoesNotKnow")),
                new DocSection("docs.modPack.heading.worthKnowing",
                    new DocBullet("docs.modPack.packAddsGameRather"),
                    new DocBullet("docs.modPack.nothingDoEditorTouches"))),

            new DocTopic("docs.orderWork.title",
                "docs.orderWork.summary",
                new DocSection("",
                    new DocBullet("docs.orderWork.fileThenNewPack.term", "docs.orderWork.fileThenNewPack"),
                    new DocBullet("docs.orderWork.charactersThenNpcsCharacter.term", "docs.orderWork.charactersThenNpcsCharacter"),
                    new DocBullet("docs.orderWork.placesThenMapButtons.term", "docs.orderWork.placesThenMapButtons"),
                    new DocBullet("docs.orderWork.dialoguesDialogueBelongsLevel.term", "docs.orderWork.dialoguesDialogueBelongsLevel"),
                    new DocBullet("docs.orderWork.scenesMusicSFXWallpapers.term", "docs.orderWork.scenesMusicSFXWallpapers"),
                    new DocBullet("docs.orderWork.variablesThenIntegrationVariable.term", "docs.orderWork.variablesThenIntegrationVariable"),
                    new DocBullet("docs.orderWork.validateF5FixLists.term", "docs.orderWork.validateF5FixLists")),
                new DocSection("docs.orderWork.heading.worthKnowing",
                    new DocBullet("docs.orderWork.npcDefinedOnceNpcs"),
                    new DocBullet("docs.orderWork.nothingEnforcesOrderSimply"))),

            new DocTopic("docs.thingsPointEachOther.title",
                "docs.thingsPointEachOther.summary",
                new DocSection("",
                    new DocBullet("docs.thingsPointEachOther.mostReferencesJustOther.term", "docs.thingsPointEachOther.mostReferencesJustOther"),
                    new DocBullet("docs.thingsPointEachOther.anywhereFieldMeansRoom.term", "docs.thingsPointEachOther.anywhereFieldMeansRoom"),
                    new DocBullet("docs.thingsPointEachOther.anywhereFieldMeansOne.term", "docs.thingsPointEachOther.anywhereFieldMeansOne"),
                    new DocBullet("docs.thingsPointEachOther.artAudioRelativePack.term", "docs.thingsPointEachOther.artAudioRelativePack")),
                new DocSection("docs.thingsPointEachOther.heading.worthKnowing",
                    new DocBullet("docs.thingsPointEachOther.pickAllTheseDropdowns"),
                    new DocBullet("docs.thingsPointEachOther.validateFlagsTokenDoes"),
                    new DocBullet("docs.thingsPointEachOther.renamingItemLeavesEverything"))),

            new DocTopic("docs.puttingValuesIntoText.title",
                "docs.puttingValuesIntoText.summary",
                new DocSection("",
                    new DocBullet("docs.puttingValuesIntoText.dialogueTextButtonLabels.term", "docs.puttingValuesIntoText.dialogueTextButtonLabels"),
                    new DocBullet("docs.puttingValuesIntoText.dialogueTextPlayerS.term", "docs.puttingValuesIntoText.dialogueTextPlayerS"),
                    new DocBullet("docs.puttingValuesIntoText.playerCallsTheirMother.term", "docs.puttingValuesIntoText.playerCallsTheirMother"),
                    new DocBullet("docs.puttingValuesIntoText.wordChildFamilyS.term", "docs.puttingValuesIntoText.wordChildFamilyS"),
                    new DocBullet("docs.puttingValuesIntoText.playerCallsFamily.term", "docs.puttingValuesIntoText.playerCallsFamily"),
                    new DocBullet("docs.puttingValuesIntoText.writeTheseRatherThan"),
                    new DocBullet("docs.puttingValuesIntoText.thoseSevenOnesKnown"),
                    new DocBullet("docs.puttingValuesIntoText.actionConditionValueBox.term", "docs.puttingValuesIntoText.actionConditionValueBox"),
                    new DocBullet("docs.puttingValuesIntoText.literalDollarSignRare.term", "docs.puttingValuesIntoText.literalDollarSignRare"),
                    new DocBullet("docs.puttingValuesIntoText.integrationRuleRepeatsOver.term", "docs.puttingValuesIntoText.integrationRuleRepeatsOver")),
                new DocSection("docs.puttingValuesIntoText.heading.markupLine",
                    new DocBullet("docs.puttingValuesIntoText.setsTextSizeRest.term", "docs.puttingValuesIntoText.setsTextSizeRest"),
                    new DocBullet("docs.puttingValuesIntoText.boldItalicColouredText.term", "docs.puttingValuesIntoText.boldItalicColouredText"),
                    new DocBullet("docs.puttingValuesIntoText.writtenRRGGBBRRGGBBAATransparency.term", "docs.puttingValuesIntoText.writtenRRGGBBRRGGBBAATransparency"),
                    new DocBullet("docs.puttingValuesIntoText.formattingButtonsOverText"),
                    new DocBullet("docs.puttingValuesIntoText.tagNotUnderstoodShown")),
                new DocSection("docs.puttingValuesIntoText.heading.worthKnowing",
                    new DocBullet("docs.puttingValuesIntoText.twoSeparateBracedToken"),
                    new DocBullet("docs.puttingValuesIntoText.conditionActionCanStill"),
                    new DocBullet("docs.puttingValuesIntoText.variableHasNeverBeen"))),

            new DocTopic("docs.whenSomethingDoesNotWork.title",
                "docs.whenSomethingDoesNotWork.summary",
                new DocSection("",
                    new DocBullet("docs.whenSomethingDoesNotWork.everyCheckAcrossWhole.term", "docs.whenSomethingDoesNotWork.everyCheckAcrossWhole"),
                    new DocBullet("docs.whenSomethingDoesNotWork.theyComposeArtExactly.term", "docs.whenSomethingDoesNotWork.theyComposeArtExactly"),
                    new DocBullet("docs.whenSomethingDoesNotWork.flagDialogueConditionDebugging.term", "docs.whenSomethingDoesNotWork.flagDialogueConditionDebugging")),
                new DocSection("docs.whenSomethingDoesNotWork.heading.worthKnowing",
                    new DocBullet("docs.whenSomethingDoesNotWork.packDoesNotAppear"),
                    new DocBullet("docs.whenSomethingDoesNotWork.emptyPreviewPackHave"),
                    new DocBullet("docs.whenSomethingDoesNotWork.bothLoggingFlagsStored")))),

        new DocPart("docs.part.concepts",

            new DocTopic("docs.packsSmspack.title",
                "docs.packsSmspack.summary",
                new DocSection("",
                    new DocBullet("docs.packsSmspack.whereWorkHoldsModpack.term", "docs.packsSmspack.whereWorkHoldsModpack"),
                    new DocBullet("docs.packsSmspack.everythingAuthorEditorCharacters.term", "docs.packsSmspack.everythingAuthorEditorCharacters"),
                    new DocBullet("docs.packsSmspack.singleFileGameLoads.term", "docs.packsSmspack.singleFileGameLoads"),
                    new DocBullet("docs.packsSmspack.dropSmspackIntoBepinex.term", "docs.packsSmspack.dropSmspackIntoBepinex")),
                new DocSection("docs.packsSmspack.heading.worthKnowing",
                    new DocBullet("docs.packsSmspack.becausePathsInsideArchive"),
                    new DocBullet("docs.packsSmspack.packOwnsWholeFolder"),
                    new DocBullet("docs.packsSmspack.versionControlFoldersEditor"))),

            new DocTopic("docs.runtimeNamesDisplayNames.title",
                "docs.runtimeNamesDisplayNames.summary",
                new DocSection("",
                    new DocBullet("docs.runtimeNamesDisplayNames.identifierEverythingElsePoints.term", "docs.runtimeNamesDisplayNames.identifierEverythingElsePoints"),
                    new DocBullet("docs.runtimeNamesDisplayNames.editorSListsShow.term", "docs.runtimeNamesDisplayNames.editorSListsShow")),
                new DocSection("docs.runtimeNamesDisplayNames.heading.worthKnowing",
                    new DocBullet("docs.runtimeNamesDisplayNames.dialogueNodeSActor"),
                    new DocBullet("docs.runtimeNamesDisplayNames.editMenuCallsSame"),
                    new DocBullet("docs.runtimeNamesDisplayNames.twoItemsSameKind"),
                    new DocBullet("docs.runtimeNamesDisplayNames.renamingOneLeavesAnything"))),

            new DocTopic("docs.foldersLists.title",
                "docs.foldersLists.summary",
                new DocSection("",
                    new DocBullet("docs.foldersLists.makeFolderCurrentTab.term", "docs.foldersLists.makeFolderCurrentTab"),
                    new DocBullet("docs.foldersLists.foldersSavedPackBut"),
                    new DocBullet("docs.foldersLists.renamingFolderMovingItems"))),

            new DocTopic("docs.conditionActionLists.title",
                "docs.conditionActionLists.summary",
                new DocSection("",
                    new DocBullet("docs.conditionActionLists.addRequirementEveryCondition.term", "docs.conditionActionLists.addRequirementEveryCondition"),
                    new DocBullet("docs.conditionActionLists.addSomethingDoWhen.term", "docs.conditionActionLists.addSomethingDoWhen"),
                    new DocBullet("docs.conditionActionLists.bundleConditionsWayBrackets.term", "docs.conditionActionLists.bundleConditionsWayBrackets"),
                    new DocBullet("docs.conditionActionLists.moveWholeListSomewhere.term", "docs.conditionActionLists.moveWholeListSomewhere")),
                new DocSection("docs.conditionActionLists.heading.worthKnowing",
                    new DocBullet("docs.conditionActionLists.clipboardSharedAcrossDialogues"),
                    new DocBullet("docs.conditionActionLists.dialogueSStartConditions"))),

            new DocTopic("docs.maskPainter.title",
                "docs.maskPainter.summary",
                new DocSection("",
                    new DocBullet("docs.maskPainter.maskNotArtworkRecords"),
                    new DocBullet("docs.maskPainter.characterNPCMaskHas.term", "docs.maskPainter.characterNPCMaskHas"),
                    new DocBullet("docs.maskPainter.realArtUnderneathThere.term", "docs.maskPainter.realArtUnderneathThere"),
                    new DocBullet("docs.maskPainter.brushEraserSizeHardness.term", "docs.maskPainter.brushEraserSizeHardness"),
                    new DocBullet("docs.maskPainter.makesOpacitySliderCeiling.term", "docs.maskPainter.makesOpacitySliderCeiling"),
                    new DocBullet("docs.maskPainter.emptyCompletelyFillLayer.term", "docs.maskPainter.emptyCompletelyFillLayer"),
                    new DocBullet("docs.maskPainter.writeMaskBackFile.term", "docs.maskPainter.writeMaskBackFile")),
                new DocSection("docs.maskPainter.heading.whichLayerMoves",
                    new DocBullet("docs.maskPainter.upDownSpeedSets.term", "docs.maskPainter.upDownSpeedSets"),
                    new DocBullet("docs.maskPainter.sideSideRippleRunning.term", "docs.maskPainter.sideSideRippleRunning"),
                    new DocBullet("docs.maskPainter.driftingIrregularWobbleBoth.term", "docs.maskPainter.driftingIrregularWobbleBoth"),
                    new DocBullet("docs.maskPainter.placeMaskThereOnly.term", "docs.maskPainter.placeMaskThereOnly"),
                    new DocBullet("docs.maskPainter.sixSettingsSitUnder")),
                new DocSection("docs.maskPainter.heading.hotkeys",
                    new DocBullet("docs.maskPainter.brushEraser.term", "docs.maskPainter.brushEraser"),
                    new DocBullet("docs.maskPainter.switchBounceWaveNoise.term", "docs.maskPainter.switchBounceWaveNoise"),
                    new DocBullet("docs.maskPainter.showHideBounceWave.term", "docs.maskPainter.showHideBounceWave"),
                    new DocBullet("docs.maskPainter.showHideReferenceArt.term", "docs.maskPainter.showHideReferenceArt"),
                    new DocBullet("docs.maskPainter.smallerLargerBrush.term", "docs.maskPainter.smallerLargerBrush"),
                    new DocBullet("docs.maskPainter.lessMoreOpacityHold.term", "docs.maskPainter.lessMoreOpacityHold"),
                    new DocBullet("docs.maskPainter.sliderHaveClickedOne.term", "docs.maskPainter.sliderHaveClickedOne"),
                    new DocBullet("docs.maskPainter.clearFillLayer.term", "docs.maskPainter.clearFillLayer"),
                    new DocBullet("docs.maskPainter.undoRedo.term", "docs.maskPainter.undoRedo"),
                    new DocBullet("docs.maskPainter.saveMaskFile.term", "docs.maskPainter.saveMaskFile"),
                    new DocBullet("docs.maskPainter.holdMiddleMouseButton.term", "docs.maskPainter.holdMiddleMouseButton")),
                new DocSection("docs.maskPainter.heading.worthKnowing",
                    new DocBullet("docs.maskPainter.fileItselfCharacterMask"))),

            new DocTopic("docs.previews.title",
                "docs.previews.summary",
                new DocSection("",
                    new DocBullet("docs.previews.previewsComposeArtWay"),
                    new DocBullet("docs.previews.theyDoNotRun"),
                    new DocBullet("docs.previews.previewsResolveImagePaths"),
                    new DocBullet("docs.previews.previewQualityOptionsMenu")))),

        new DocPart("docs.part.workspace",

            new DocTopic("docs.fileMenu.title",
                "docs.fileMenu.summary",
                new DocSection("",
                    new DocBullet("docs.fileMenu.startEmptyPackSave.term", "docs.fileMenu.startEmptyPackSave"),
                    new DocBullet("docs.fileMenu.openPackFolderHave.term", "docs.fileMenu.openPackFolderHave"),
                    new DocBullet("docs.fileMenu.reopenOnePacksWorked.term", "docs.fileMenu.reopenOnePacksWorked"),
                    new DocBullet("docs.fileMenu.writePackFolderDisk.term", "docs.fileMenu.writePackFolderDisk"),
                    new DocBullet("docs.fileMenu.writePackNewFolder.term", "docs.fileMenu.writePackNewFolder"),
                    new DocBullet("docs.fileMenu.saveThenBundleFolder.term", "docs.fileMenu.saveThenBundleFolder"),
                    new DocBullet("docs.fileMenu.sameButAlwaysAsks.term", "docs.fileMenu.sameButAlwaysAsks"),
                    new DocBullet("docs.fileMenu.reRunEveryCheck.term", "docs.fileMenu.reRunEveryCheck"),
                    new DocBullet("docs.fileMenu.packTranslations.term", "docs.fileMenu.packTranslations")),
                new DocSection("docs.fileMenu.heading.worthKnowing",
                    new DocBullet("docs.fileMenu.bothExportItemsStay"),
                    new DocBullet("docs.fileMenu.exportLocationRememberedEditor"))),

            new DocTopic("docs.editMenu.title",
                "docs.editMenu.summary",
                new DocSection("",
                    new DocBullet("docs.editMenu.copySelectedItemInto.term", "docs.editMenu.copySelectedItemInto"),
                    new DocBullet("docs.editMenu.copySelectedItemCan.term", "docs.editMenu.copySelectedItemCan"),
                    new DocBullet("docs.editMenu.pasteCopiedItemInto.term", "docs.editMenu.pasteCopiedItemInto"),
                    new DocBullet("docs.editMenu.changeSelectedItemS.term", "docs.editMenu.changeSelectedItemS"),
                    new DocBullet("docs.editMenu.removeSelectedItemPack.term", "docs.editMenu.removeSelectedItemPack")),
                new DocSection("docs.editMenu.heading.worthKnowing",
                    new DocBullet("docs.editMenu.renamingVariableTrueRename"),
                    new DocBullet("docs.editMenu.renamingAnythingElseChanges"),
                    new DocBullet("docs.editMenu.eachShortcutAlsoWorks"),
                    new DocBullet("docs.editMenu.modforgeTabHasNo"))),

            new DocTopic("docs.optionsMenu.title",
                "docs.optionsMenu.summary",
                new DocSection("",
                    new DocBullet("docs.optionsMenu.listEverythingSaveWill.term", "docs.optionsMenu.listEverythingSaveWill"),
                    new DocBullet("docs.optionsMenu.underlineMisspellingsNodeS.term", "docs.optionsMenu.underlineMisspellingsNodeS"),
                    new DocBullet("docs.optionsMenu.addEveryCharacterPlace.term", "docs.optionsMenu.addEveryCharacterPlace"),
                    new DocBullet("docs.optionsMenu.tradePreviewSmoothnessAgainst.term", "docs.optionsMenu.tradePreviewSmoothnessAgainst")),
                new DocSection("docs.optionsMenu.heading.worthKnowing",
                    new DocBullet("docs.optionsMenu.windowsDictionarySharedRest"))),

            new DocTopic("docs.themes.title",
                "docs.themes.summary",
                new DocSection("",
                    new DocBullet("docs.themes.lightSlateForestPlum.term", "docs.themes.lightSlateForestPlum"),
                    new DocBullet("docs.themes.darkMidnightCarbon.term", "docs.themes.darkMidnightCarbon"),
                    new DocBullet("docs.themes.themesChangeEditorOnly"))),

            new DocTopic("docs.modforgeTab.title",
                "docs.modforgeTab.summary",
                new DocSection("docs.modforgeTab.heading.learning",
                    new DocBullet("docs.modforgeTab.fourStepsPackGoes.term", "docs.modforgeTab.fourStepsPackGoes"),
                    new DocBullet("docs.modforgeTab.sevenWalkthroughsBuildReal.term", "docs.modforgeTab.sevenWalkthroughsBuildReal"),
                    new DocBullet("docs.modforgeTab.referenceSearchBoxMatches.term", "docs.modforgeTab.referenceSearchBoxMatches"),
                    new DocBullet("docs.modforgeTab.tutorialsKeepTheyMake"),
                    new DocBullet("docs.modforgeTab.finishedTutorialTickedButton")),
                new DocSection("docs.modforgeTab.heading.issues",
                    new DocBullet("docs.modforgeTab.reRunEveryCheck.term", "docs.modforgeTab.reRunEveryCheck"),
                    new DocBullet("docs.modforgeTab.oneRowPerProblem.term", "docs.modforgeTab.oneRowPerProblem"),
                    new DocBullet("docs.modforgeTab.somethingWillNotWork.term", "docs.modforgeTab.somethingWillNotWork"),
                    new DocBullet("docs.modforgeTab.somethingSuspiciousMayStill.term", "docs.modforgeTab.somethingSuspiciousMayStill"),
                    new DocBullet("docs.modforgeTab.noteWorthReadingNothing.term", "docs.modforgeTab.noteWorthReadingNothing"),
                    new DocBullet("docs.modforgeTab.countAlsoSitsStatus")),
                new DocSection("docs.modforgeTab.heading.debugTracking",
                    new DocBullet("docs.modforgeTab.dialoguesHaveFlaggedDialogues.term", "docs.modforgeTab.dialoguesHaveFlaggedDialogues"),
                    new DocBullet("docs.modforgeTab.integrationRulesHaveFlagged.term", "docs.modforgeTab.integrationRulesHaveFlagged"),
                    new DocBullet("docs.modforgeTab.stopTrackingOneItem.term", "docs.modforgeTab.stopTrackingOneItem"),
                    new DocBullet("docs.modforgeTab.clearWholeList.term", "docs.modforgeTab.clearWholeList"),
                    new DocBullet("docs.modforgeTab.bothListsStoredPack"))),

            new DocTopic("docs.keyboardShortcuts.title",
                "docs.keyboardShortcuts.summary",
                new DocSection("docs.keyboardShortcuts.heading.pack",
                    new DocBullet("docs.keyboardShortcuts.newPack.term", "docs.keyboardShortcuts.newPack"),
                    new DocBullet("docs.keyboardShortcuts.openPack.term", "docs.keyboardShortcuts.openPack"),
                    new DocBullet("docs.keyboardShortcuts.save.term", "docs.keyboardShortcuts.save"),
                    new DocBullet("docs.keyboardShortcuts.save2.term", "docs.keyboardShortcuts.save2"),
                    new DocBullet("docs.keyboardShortcuts.exportPack.term", "docs.keyboardShortcuts.exportPack"),
                    new DocBullet("docs.keyboardShortcuts.exportPack2.term", "docs.keyboardShortcuts.exportPack2"),
                    new DocBullet("docs.keyboardShortcuts.validate.term", "docs.keyboardShortcuts.validate")),
                new DocSection("docs.keyboardShortcuts.heading.selectedItem",
                    new DocBullet("docs.keyboardShortcuts.duplicate.term", "docs.keyboardShortcuts.duplicate"),
                    new DocBullet("docs.keyboardShortcuts.copy.term", "docs.keyboardShortcuts.copy"),
                    new DocBullet("docs.keyboardShortcuts.paste.term", "docs.keyboardShortcuts.paste"),
                    new DocBullet("docs.keyboardShortcuts.rename.term", "docs.keyboardShortcuts.rename"),
                    new DocBullet("docs.keyboardShortcuts.delete.term", "docs.keyboardShortcuts.delete")))),

        new DocPart("docs.part.tabs",

            new DocTopic("docs.characters.title",
                "docs.characters.summary",
                new DocSection("docs.characters.heading.addingOne",
                    new DocBullet("docs.characters.characterPackDrawsBust.term", "docs.characters.characterPackDrawsBust"),
                    new DocBullet("docs.characters.characterWhoBorrowsOne.term", "docs.characters.characterWhoBorrowsOne"),
                    new DocBullet("docs.characters.speakingPartNoBust.term", "docs.characters.speakingPartNoBust"),
                    new DocBullet("docs.characters.deleteCharacterAllOutfits.term", "docs.characters.deleteCharacterAllOutfits")),
                new DocSection("docs.characters.heading.player",
                    new DocBullet("docs.characters.everyPackHasPlayer"),
                    new DocBullet("docs.characters.typingVoiceStillYours"),
                    new DocBullet("docs.characters.useSpeakerAnyLine")),
                new DocSection("docs.characters.heading.identity",
                    new DocBullet("docs.characters.playerReadsSpeechLine.term", "docs.characters.playerReadsSpeechLine"),
                    new DocBullet("docs.characters.pronouns.term", "docs.characters.pronouns"),
                    new DocBullet("docs.characters.tintsSpeakerNameLeave.term", "docs.characters.tintsSpeakerNameLeave"),
                    new DocBullet("docs.characters.whereCharacterSArt.term", "docs.characters.whereCharacterSArt"),
                    new DocBullet("docs.characters.whichBustCharacterAppears.term", "docs.characters.whichBustCharacterAppears"),
                    new DocBullet("docs.characters.dialogueNodeNamesSpeaker.term", "docs.characters.dialogueNodeNamesSpeaker"),
                    new DocBullet("docs.characters.objectBustBuiltUnder.term", "docs.characters.objectBustBuiltUnder")),
                new DocSection("docs.characters.heading.outfits",
                    new DocBullet("docs.characters.outfitOneCompleteBust"),
                    new DocBullet("docs.characters.addDeleteOutfitSelected.term", "docs.characters.addDeleteOutfitSelected"),
                    new DocBullet("docs.characters.dialogueLinesActionsRefer.term", "docs.characters.dialogueLinesActionsRefer")),
                new DocSection("docs.characters.heading.voiceTypewriterBlip",
                    new DocBullet("docs.characters.whenOffCharacterS.term", "docs.characters.whenOffCharacterS"),
                    new DocBullet("docs.characters.maleFemaleFillUsual.term", "docs.characters.maleFemaleFillUsual"),
                    new DocBullet("docs.characters.oftenBlipFiresText.term", "docs.characters.oftenBlipFiresText"),
                    new DocBullet("docs.characters.rangeEachBlipS.term", "docs.characters.rangeEachBlipS")),
                new DocSection("docs.characters.heading.speechExpressions",
                    new DocBullet("docs.characters.everyCharacterStartsGreyed.term", "docs.characters.everyCharacterStartsGreyed"),
                    new DocBullet("docs.characters.mapKeyWillUse.term", "docs.characters.mapKeyWillUse")),
                new DocSection("docs.characters.heading.sprites",
                    new DocBullet("docs.characters.bustItselfPathsRelative.term", "docs.characters.bustItselfPathsRelative"),
                    new DocBullet("docs.characters.decidesWhereJiggleEffect.term", "docs.characters.decidesWhereJiggleEffect"),
                    new DocBullet("docs.characters.untickCharacterNoBlink.term", "docs.characters.untickCharacterNoBlink"),
                    new DocBullet("docs.characters.eyesClosedOverlayWhen.term", "docs.characters.eyesClosedOverlayWhen"),
                    new DocBullet("docs.characters.turnWhenBustHas.term", "docs.characters.turnWhenBustHas"),
                    new DocBullet("docs.characters.sameExpressionArtwork.term", "docs.characters.sameExpressionArtwork")),
                new DocSection("docs.characters.heading.jiggle",
                    new DocBullet("docs.characters.theseSayBustMoves"),
                    new DocBullet("docs.characters.fastCycleRunsFar.term", "docs.characters.fastCycleRunsFar"),
                    new DocBullet("docs.characters.manyWavesFitDown.term", "docs.characters.manyWavesFitDown"),
                    new DocBullet("docs.characters.fineIrregularDriftFast.term", "docs.characters.fineIrregularDriftFast"),
                    new DocBullet("docs.characters.multipliesBustSColour.term", "docs.characters.multipliesBustSColour"),
                    new DocBullet("docs.characters.roundsMovementWholePixels.term", "docs.characters.roundsMovementWholePixels")),
                new DocSection("docs.characters.heading.particles",
                    new DocBullet("docs.characters.startWetEffectAlready.term", "docs.characters.startWetEffectAlready")),
                new DocSection("docs.characters.heading.preview",
                    new DocBullet("docs.characters.showBustOneParticular.term", "docs.characters.showBustOneParticular"),
                    new DocBullet("docs.characters.animatePreviewSoCan.term", "docs.characters.animatePreviewSoCan"),
                    new DocBullet("docs.characters.farBustBobsPreview.term", "docs.characters.farBustBobsPreview"))),

            new DocTopic("docs.npcs.title",
                "docs.npcs.summary",
                new DocSection("docs.npcs.heading.list",
                    new DocBullet("docs.npcs.addNPCDefinition.term", "docs.npcs.addNPCDefinition"),
                    new DocBullet("docs.npcs.organiseListRemovingFolder.term", "docs.npcs.organiseListRemovingFolder"),
                    new DocBullet("docs.npcs.ctrlClickShiftClick")),
                new DocSection("docs.npcs.heading.identity",
                    new DocBullet("docs.npcs.readList.term", "docs.npcs.readList"),
                    new DocBullet("docs.npcs.placementPlacesTabRefers.term", "docs.npcs.placementPlacesTabRefers")),
                new DocSection("docs.npcs.heading.spriteMask",
                    new DocBullet("docs.npcs.artworkAnyResolutionRead.term", "docs.npcs.artworkAnyResolutionRead"),
                    new DocBullet("docs.npcs.whereJiggleAppliesPainted.term", "docs.npcs.whereJiggleAppliesPainted"),
                    new DocBullet("docs.npcs.farForwardNPCDraws.term", "docs.npcs.farForwardNPCDraws")),
                new DocSection("docs.npcs.heading.jiggle",
                    new DocBullet("docs.npcs.sameSixSettingsCharacter"),
                    new DocBullet("docs.npcs.fastCycleRunsFar.term", "docs.npcs.fastCycleRunsFar"),
                    new DocBullet("docs.npcs.tightSideSideRipple.term", "docs.npcs.tightSideSideRipple"),
                    new DocBullet("docs.npcs.irregularDriftNoiseLayer.term", "docs.npcs.irregularDriftNoiseLayer"),
                    new DocBullet("docs.npcs.colourMultiplierWhetherMovement.term", "docs.npcs.colourMultiplierWhetherMovement")),
                new DocSection("docs.npcs.heading.blink",
                    new DocBullet("docs.npcs.eyesClosedArtworkLeave.term", "docs.npcs.eyesClosedArtworkLeave"),
                    new DocBullet("docs.npcs.longEyesStayOpen.term", "docs.npcs.longEyesStayOpen"),
                    new DocBullet("docs.npcs.longBlinkLasts.term", "docs.npcs.longBlinkLasts")),
                new DocSection("docs.npcs.heading.reflection",
                    new DocBullet("docs.npcs.drawMirroredCopyBeneath.term", "docs.npcs.drawMirroredCopyBeneath"),
                    new DocBullet("docs.npcs.visibleGameSOwn.term", "docs.npcs.visibleGameSOwn"),
                    new DocBullet("docs.npcs.reflectionTakesColourWhatever.term", "docs.npcs.reflectionTakesColourWhatever"),
                    new DocBullet("docs.npcs.whereSitsFarForward.term", "docs.npcs.whereSitsFarForward")),
                new DocSection("docs.npcs.heading.shadow",
                    new DocBullet("docs.npcs.drawSimpleShadowUnder.term", "docs.npcs.drawSimpleShadowUnder"),
                    new DocBullet("docs.npcs.shadeFarForwardDraws.term", "docs.npcs.shadeFarForwardDraws")),
                new DocSection("docs.npcs.heading.wetParticles",
                    new DocBullet("docs.npcs.whetherNPCHasWet.term", "docs.npcs.whetherNPCHasWet")),
                new DocSection("docs.npcs.heading.preview",
                    new DocBullet("docs.npcs.showsPoseJiggleShadow"))),

            new DocTopic("docs.places.title",
                "docs.places.summary",
                new DocSection("docs.places.heading.twoLists",
                    new DocBullet("docs.places.locationsPackBuildsOwn.term", "docs.places.locationsPackBuildsOwn"),
                    new DocBullet("docs.places.placeAlreadyExistsGame.term", "docs.places.placeAlreadyExistsGame")),
                new DocSection("docs.places.heading.identity",
                    new DocBullet("docs.places.vanillaExtensionOnlyWhich.term", "docs.places.vanillaExtensionOnlyWhich"),
                    new DocBullet("docs.places.namePlayersReadNavigator.term", "docs.places.namePlayersReadNavigator"),
                    new DocBullet("docs.places.conditionsActionsNavigatorTargets.term", "docs.places.conditionsActionsNavigatorTargets"),
                    new DocBullet("docs.places.objectLevelBuiltGame.term", "docs.places.objectLevelBuiltGame")),
                new DocSection("docs.places.heading.levelArt",
                    new DocBullet("docs.places.layerDrawnBehindSorting.term", "docs.places.layerDrawnBehindSorting"),
                    new DocBullet("docs.places.layerDrawnFront10.term", "docs.places.layerDrawnFront10"),
                    new DocBullet("docs.places.farForwardEachTwo.term", "docs.places.farForwardEachTwo"),
                    new DocBullet("docs.places.optionalMasksShapingEach.term", "docs.places.optionalMasksShapingEach"),
                    new DocBullet("docs.places.packFileCallsThese.term", "docs.places.packFileCallsThese")),
                new DocSection("docs.places.heading.behaviour",
                    new DocBullet("docs.places.farFrontLayerSlides.term", "docs.places.farFrontLayerSlides"),
                    new DocBullet("docs.places.backLayerSOwn.term", "docs.places.backLayerSOwn"),
                    new DocBullet("docs.places.driftCursorInsteadAgainst.term", "docs.places.driftCursorInsteadAgainst"),
                    new DocBullet("docs.places.carryOceanAmbienceSeagull.term", "docs.places.carryOceanAmbienceSeagull"),
                    new DocBullet("docs.places.whetherGameSRain.term", "docs.places.whetherGameSRain")),
                new DocSection("docs.places.heading.contents",
                    new DocBullet("docs.places.addButtonPlaceS.term", "docs.places.addButtonPlaceS"),
                    new DocBullet("docs.places.addObjectRoomArt.term", "docs.places.addObjectRoomArt"),
                    new DocBullet("docs.places.placeOneNpcsInto.term", "docs.places.placeOneNpcsInto"),
                    new DocBullet("docs.places.vanillaExtensionAddEntry.term", "docs.places.vanillaExtensionAddEntry")),
                new DocSection("docs.places.heading.enterExit",
                    new DocBullet("docs.places.actionsRunOnceWhen.term", "docs.places.actionsRunOnceWhen")),
                new DocSection("docs.places.heading.preview",
                    new DocBullet("docs.places.gameDrawsNothingBeneath.term", "docs.places.gameDrawsNothingBeneath"),
                    new DocBullet("docs.places.sameObjectsParkedRule.term", "docs.places.sameObjectsParkedRule"),
                    new DocBullet("docs.places.driftSceneCursorGame.term", "docs.places.driftSceneCursorGame"),
                    new DocBullet("docs.places.runRealJigglePass.term", "docs.places.runRealJigglePass"))),

            new DocTopic("docs.mapButtons.title",
                "docs.mapButtons.summary",
                new DocSection("",
                    new DocBullet("docs.mapButtons.addButtonWorldMap.term", "docs.mapButtons.addButtonWorldMap"),
                    new DocBullet("docs.mapButtons.whereButtonTakesPlayer.term", "docs.mapButtons.whereButtonTakesPlayer"),
                    new DocBullet("docs.mapButtons.whichWorldMapS.term", "docs.mapButtons.whichWorldMapS"),
                    new DocBullet("docs.mapButtons.buttonSTextAccepts.term", "docs.mapButtons.buttonSTextAccepts"),
                    new DocBullet("docs.mapButtons.trackSwitchWhenButton.term", "docs.mapButtons.trackSwitchWhenButton"),
                    new DocBullet("docs.mapButtons.gateButtonSoOnly.term", "docs.mapButtons.gateButtonSoOnly"),
                    new DocBullet("docs.mapButtons.deleteSelectedMapButton.term", "docs.mapButtons.deleteSelectedMapButton"))),

            new DocTopic("docs.dialogues.title",
                "docs.dialogues.summary",
                new DocSection("docs.dialogues.heading.identity",
                    new DocBullet("docs.dialogues.readList.term", "docs.dialogues.readList"),
                    new DocBullet("docs.dialogues.jumpsLogsOtherPacks.term", "docs.dialogues.jumpsLogsOtherPacks"),
                    new DocBullet("docs.dialogues.whenSeveralDialoguesBecome.term", "docs.dialogues.whenSeveralDialoguesBecome")),
                new DocSection("docs.dialogues.heading.starts",
                    new DocBullet("docs.dialogues.hasTrueDialoguePlay.term", "docs.dialogues.hasTrueDialoguePlay"),
                    new DocBullet("docs.dialogues.holdBackRoomS.term", "docs.dialogues.holdBackRoomS"),
                    new DocBullet("docs.dialogues.playArrivalUsualStay.term", "docs.dialogues.playArrivalUsualStay"),
                    new DocBullet("docs.dialogues.doNotPlayArrival.term", "docs.dialogues.doNotPlayArrival"),
                    new DocBullet("docs.dialogues.ifSomethingElsePlaying.term", "docs.dialogues.ifSomethingElsePlaying"),
                    new DocBullet("docs.dialogues.gameF12LogsWhich.term", "docs.dialogues.gameF12LogsWhich")),
                new DocSection("docs.dialogues.heading.gameSConversations",
                    new DocBullet("docs.dialogues.gameChecksBeforePlays.term", "docs.dialogues.gameChecksBeforePlays"),
                    new DocBullet("docs.dialogues.lineOneGameS.term", "docs.dialogues.lineOneGameS")),
                new DocSection("docs.dialogues.heading.nodes",
                    new DocBullet("docs.dialogues.dialogueTreePlayStarts"),
                    new DocBullet("docs.dialogues.addNodeTopLevel.term", "docs.dialogues.addNodeTopLevel"),
                    new DocBullet("docs.dialogues.addChildSelectedNode.term", "docs.dialogues.addChildSelectedNode"),
                    new DocBullet("docs.dialogues.sameButBesideSelected.term", "docs.dialogues.sameButBesideSelected"),
                    new DocBullet("docs.dialogues.textTagNeverCarry"),
                    new DocBullet("docs.dialogues.deleteSelectedNodeAnything.term", "docs.dialogues.deleteSelectedNodeAnything"),
                    new DocBullet("docs.dialogues.copyNodeEverythingBeneath.term", "docs.dialogues.copyNodeEverythingBeneath"),
                    new DocBullet("docs.dialogues.whereCopyLandsBeside.term", "docs.dialogues.whereCopyLandsBeside")),
                new DocSection("docs.dialogues.heading.selectedNode",
                    new DocBullet("docs.dialogues.textPlaysLineChoice.term", "docs.dialogues.textPlaysLineChoice"),
                    new DocBullet("docs.dialogues.whoSpeakingTheyLook.term", "docs.dialogues.whoSpeakingTheyLook"),
                    new DocBullet("docs.dialogues.lineItselfPVName.term", "docs.dialogues.lineItselfPVName"),
                    new DocBullet("docs.dialogues.optionalLabelSoAnother.term", "docs.dialogues.optionalLabelSoAnother"),
                    new DocBullet("docs.dialogues.wherePlayGoesAfter.term", "docs.dialogues.wherePlayGoesAfter"),
                    new DocBullet("docs.dialogues.whichTaggedNodeResume.term", "docs.dialogues.whichTaggedNodeResume"),
                    new DocBullet("docs.dialogues.veryBottomDialogueContinue"),
                    new DocBullet("docs.dialogues.untilinteractionWaitsPlayerTimeout.term", "docs.dialogues.untilinteractionWaitsPlayerTimeout"),
                    new DocBullet("docs.dialogues.longFinishedLineLingers.term", "docs.dialogues.longFinishedLineLingers")),
                new DocSection("docs.dialogues.heading.perNodeConditionsActions",
                    new DocBullet("docs.dialogues.skipNodeWhenThey.term", "docs.dialogues.skipNodeWhenThey"),
                    new DocBullet("docs.dialogues.runLineBegins.term", "docs.dialogues.runLineBegins"),
                    new DocBullet("docs.dialogues.runLineEndsUsual.term", "docs.dialogues.runLineEndsUsual"))),

            new DocTopic("docs.scenes.title",
                "docs.scenes.summary",
                new DocSection("docs.scenes.heading.identity",
                    new DocBullet("docs.scenes.readList.term", "docs.scenes.readList"),
                    new DocBullet("docs.scenes.actionsConditionsReferScene.term", "docs.scenes.actionsConditionsReferScene")),
                new DocSection("docs.scenes.heading.sceneImage",
                    new DocBullet("docs.scenes.artworkRelativePackFolder.term", "docs.scenes.artworkRelativePackFolder")),
                new DocSection("docs.scenes.heading.frame",
                    new DocBullet("docs.scenes.useOneBordersShip.term", "docs.scenes.useOneBordersShip"),
                    new DocBullet("docs.scenes.useOwnBorderInstead.term", "docs.scenes.useOwnBorderInstead")),
                new DocSection("docs.scenes.heading.sound",
                    new DocBullet("docs.scenes.silentPlaysNothingDefault.term", "docs.scenes.silentPlaysNothingDefault")),
                new DocSection("docs.scenes.heading.worthKnowing",
                    new DocBullet("docs.scenes.scenesShownHiddenActions"))),

            new DocTopic("docs.music.title",
                "docs.music.summary",
                new DocSection("docs.music.heading.identity",
                    new DocBullet("docs.music.readList.term", "docs.music.readList"),
                    new DocBullet("docs.music.musicSwitchingActionRefers.term", "docs.music.musicSwitchingActionRefers")),
                new DocSection("docs.music.heading.audio",
                    new DocBullet("docs.music.audioFileRelativePack.term", "docs.music.audioFileRelativePack"),
                    new DocBullet("docs.music.whetherTrackRepeatsLeave.term", "docs.music.whetherTrackRepeatsLeave"),
                    new DocBullet("docs.music.loudPlays01.term", "docs.music.loudPlays01")),
                new DocSection("docs.music.heading.preview",
                    new DocBullet("docs.music.hearTrackVolumeAbove.term", "docs.music.hearTrackVolumeAbove"))),

            new DocTopic("docs.sfx.title",
                "docs.sfx.summary",
                new DocSection("docs.sfx.heading.identity",
                    new DocBullet("docs.sfx.readList.term", "docs.sfx.readList"),
                    new DocBullet("docs.sfx.playSoundActionRefers.term", "docs.sfx.playSoundActionRefers")),
                new DocSection("docs.sfx.heading.audio",
                    new DocBullet("docs.sfx.audioFileRelativePack.term", "docs.sfx.audioFileRelativePack"),
                    new DocBullet("docs.sfx.usedWheneverSomethingPlays.term", "docs.sfx.usedWheneverSomethingPlays"),
                    new DocBullet("docs.sfx.hearDefaultVolumeNeeds.term", "docs.sfx.hearDefaultVolumeNeeds")),
                new DocSection("docs.sfx.heading.autoTriggerPatterns",
                    new DocBullet("docs.sfx.commaSeparatedListText"),
                    new DocBullet("docs.sfx.conventionLowercaseWordBetween"),
                    new DocBullet("docs.sfx.leaveBlankEffectShould")),
                new DocSection("docs.sfx.heading.variants",
                    new DocBullet("docs.sfx.effectCanHaveSeveral"),
                    new DocBullet("docs.sfx.thereNoFieldThem"),
                    new DocBullet("docs.sfx.numberThemWithoutGaps"),
                    new DocBullet("docs.sfx.extensionsDoNotHave"),
                    new DocBullet("docs.sfx.playAbovePreviewsFirst"))),

            new DocTopic("docs.wallpapers.title",
                "docs.wallpapers.summary",
                new DocSection("docs.wallpapers.heading.identity",
                    new DocBullet("docs.wallpapers.readList.term", "docs.wallpapers.readList"),
                    new DocBullet("docs.wallpapers.actionsConditionsReferWallpaper.term", "docs.wallpapers.actionsConditionsReferWallpaper")),
                new DocSection("docs.wallpapers.heading.image",
                    new DocBullet("docs.wallpapers.imageRelativePackFolder.term", "docs.wallpapers.imageRelativePackFolder"),
                    new DocBullet("docs.wallpapers.absolutePathImageSitting.term", "docs.wallpapers.absolutePathImageSitting")),
                new DocSection("docs.wallpapers.heading.unlockConditions",
                    new DocBullet("docs.wallpapers.playerHasHaveDone"))),

            new DocTopic("docs.variables.title",
                "docs.variables.summary",
                new DocSection("docs.variables.heading.definition",
                    new DocBullet("docs.variables.conditionsActionsPVTokens.term", "docs.variables.conditionsActionsPVTokens"),
                    new DocBullet("docs.variables.boolYesNoInt.term", "docs.variables.boolYesNoInt"),
                    new DocBullet("docs.variables.startsBeforeAnythingHas.term", "docs.variables.startsBeforeAnythingHas"),
                    new DocBullet("docs.variables.boolHasOnlyTwo.term", "docs.variables.boolHasOnlyTwo"),
                    new DocBullet("docs.variables.listEntriesStartsOut.term", "docs.variables.listEntriesStartsOut"),
                    new DocBullet("docs.variables.savePlayerSGame.term", "docs.variables.savePlayerSGame"),
                    new DocBullet("docs.variables.noteYourselfShownOnly.term", "docs.variables.noteYourselfShownOnly")),
                new DocSection("docs.variables.heading.refreshing",
                    new DocBullet("docs.variables.neverLeavesVariableAlone.term", "docs.variables.neverLeavesVariableAlone"),
                    new DocBullet("docs.variables.whichPlaceReRolls.term", "docs.variables.whichPlaceReRolls"),
                    new DocBullet("docs.variables.limitsNumberGameKeeps.term", "docs.variables.limitsNumberGameKeeps")),
                new DocSection("docs.variables.heading.worthKnowing",
                    new DocBullet("docs.variables.dailyRefreshHappensWhen"),
                    new DocBullet("docs.variables.seePuttingValuesInto"))),

            new DocTopic("docs.integration.title",
                "docs.integration.summary",
                new DocSection("docs.integration.heading.identity",
                    new DocBullet("docs.integration.readList.term", "docs.integration.readList"),
                    new DocBullet("docs.integration.logsReferRule.term", "docs.integration.logsReferRule"),
                    new DocBullet("docs.integration.noteYourselfShownOnly.term", "docs.integration.noteYourselfShownOnly"),
                    new DocBullet("docs.integration.gameLogRuleDecided.term", "docs.integration.gameLogRuleDecided")),
                new DocSection("docs.integration.heading.whenFires",
                    new DocBullet("docs.integration.whenActionsRunRelative.term", "docs.integration.whenActionsRunRelative"),
                    new DocBullet("docs.integration.onceMomentConditionsStart.term", "docs.integration.onceMomentConditionsStart"),
                    new DocBullet("docs.integration.onceMomentTheyStop.term", "docs.integration.onceMomentTheyStop"),
                    new DocBullet("docs.integration.everyFrameConditionsHold.term", "docs.integration.everyFrameConditionsHold"),
                    new DocBullet("docs.integration.onceWhenGameWorld.term", "docs.integration.onceWhenGameWorld"),
                    new DocBullet("docs.integration.oncePerGameDay.term", "docs.integration.oncePerGameDay")),
                new DocSection("docs.integration.heading.conditionsActionsBranches",
                    new DocBullet("docs.integration.hasTrueSeeCondition.term", "docs.integration.hasTrueSeeCondition"),
                    new DocBullet("docs.integration.happensWhenRuleFires.term", "docs.integration.happensWhenRuleFires"),
                    new DocBullet("docs.integration.fallbackTriedWhenConditions.term", "docs.integration.fallbackTriedWhenConditions"),
                    new DocBullet("docs.integration.onceRuleHasBranches")),
                new DocSection("docs.integration.heading.repeatEach",
                    new DocBullet("docs.integration.runRuleOncePer.term", "docs.integration.runRuleOncePer"),
                    new DocBullet("docs.integration.writeBracesInsideConditions.term", "docs.integration.writeBracesInsideConditions"),
                    new DocBullet("docs.integration.everyValueGetsOwn")),
                new DocSection("docs.integration.heading.editingMode",
                    new DocBullet("docs.integration.swapPickersJSONView.term", "docs.integration.swapPickersJSONView"))),

            new DocTopic("docs.quests.title",
                "docs.quests.summary",
                new DocSection("docs.quests.heading.twoLists",
                    new DocBullet("docs.quests.questsOwnFoldersCan.term", "docs.quests.questsOwnFoldersCan"),
                    new DocBullet("docs.quests.changesGameSOwn.term", "docs.quests.changesGameSOwn")),
                new DocSection("docs.quests.heading.quest",
                    new DocBullet("docs.quests.journalCallsTextBrackets.term", "docs.quests.journalCallsTextBrackets"),
                    new DocBullet("docs.quests.questActionsConditionsName.term", "docs.quests.questActionsConditionsName"),
                    new DocBullet("docs.quests.paragraphUnderTitleJournal.term", "docs.quests.paragraphUnderTitleJournal")),
                new DocSection("docs.quests.heading.startsWhen",
                    new DocBullet("docs.quests.whenAllThemPass.term", "docs.quests.whenAllThemPass"),
                    new DocBullet("docs.quests.noStartConditionsQuest.term", "docs.quests.noStartConditionsQuest")),
                new DocSection("docs.quests.heading.resetsWhen",
                    new DocBullet("docs.quests.whenAllThemPass2.term", "docs.quests.whenAllThemPass2"),
                    new DocBullet("docs.quests.whileResetConditionsPass.term", "docs.quests.whileResetConditionsPass"),
                    new DocBullet("docs.quests.noResetConditionsQuest.term", "docs.quests.noResetConditionsQuest")),
                new DocSection("docs.quests.heading.stepsAdded",
                    new DocBullet("docs.quests.stepsAdded.leave.term", "docs.quests.stepsAdded.leave"),
                    new DocBullet("docs.quests.stepsAdded.reopen.term", "docs.quests.stepsAdded.reopen"),
                    new DocBullet("docs.quests.stepsAdded.startOver.term", "docs.quests.stepsAdded.startOver"),
                    new DocBullet("docs.quests.stepsAdded.whichNew.term", "docs.quests.stepsAdded.whichNew")),
                new DocSection("docs.quests.heading.tasks",
                    new DocBullet("docs.quests.topLevelTasksRun.term", "docs.quests.topLevelTasksRun"),
                    new DocBullet("docs.quests.listedUnderTheirTask.term", "docs.quests.listedUnderTheirTask"),
                    new DocBullet("docs.quests.questSDescriptionBecomes.term", "docs.quests.questSDescriptionBecomes"),
                    new DocBullet("docs.quests.subtaskJournalListsEvery.term", "docs.quests.subtaskJournalListsEvery"),
                    new DocBullet("docs.quests.anyTaskKeepsOut.term", "docs.quests.anyTaskKeepsOut"),
                    new DocBullet("docs.quests.taskSubtasksFinishesOrder.term", "docs.quests.taskSubtasksFinishesOrder"),
                    new DocBullet("docs.quests.givesTaskCountReaching.term", "docs.quests.givesTaskCountReaching"),
                    new DocBullet("docs.quests.questActionQuestActions.term", "docs.quests.questActionQuestActions"),
                    new DocBullet("docs.quests.conditionsFinishTaskThemselves.term", "docs.quests.conditionsFinishTaskThemselves"),
                    new DocBullet("docs.quests.actionsRunTaskFinishes.term", "docs.quests.actionsRunTaskFinishes"),
                    new DocBullet("docs.quests.onlyTaskWithoutSubtasks")),
                new DocSection("docs.quests.heading.gameSQuests",
                    new DocBullet("docs.quests.vanillaQuestsListEntry.term", "docs.quests.vanillaQuestsListEntry"),
                    new DocBullet("docs.quests.whichGameSQuests.term", "docs.quests.whichGameSQuests"),
                    new DocBullet("docs.quests.muchEntryChangesButton.term", "docs.quests.muchEntryChangesButton"),
                    new DocBullet("docs.quests.paragraphQuestShipsSo.term", "docs.quests.paragraphQuestShipsSo"),
                    new DocBullet("docs.quests.replacesParagraphWhilePack.term", "docs.quests.replacesParagraphWhilePack"),
                    new DocBullet("docs.quests.gameSTasksGame.term", "docs.quests.gameSTasksGame"),
                    new DocBullet("docs.quests.addsTopLevelTask.term", "docs.quests.addsTopLevelTask"),
                    new DocBullet("docs.quests.addsSubtaskYoursEnd.term", "docs.quests.addsSubtaskYoursEnd"),
                    new DocBullet("docs.quests.moveTaskYoursAmong.term", "docs.quests.moveTaskYoursAmong"),
                    new DocBullet("docs.quests.deletesTaskYoursTakes.term", "docs.quests.deletesTaskYoursTakes"),
                    new DocBullet("docs.quests.selectingOneOpensSame.term", "docs.quests.selectingOneOpensSame"),
                    new DocBullet("docs.quests.oneGameSTasks.term", "docs.quests.oneGameSTasks"),
                    new DocBullet("docs.quests.oneGameSTasks2.term", "docs.quests.oneGameSTasks2"),
                    new DocBullet("docs.quests.anyTaskListQuest.term", "docs.quests.anyTaskListQuest"),
                    new DocBullet("docs.quests.actionsRunOnceMoment.term", "docs.quests.actionsRunOnceMoment"),
                    new DocBullet("docs.quests.conditionsStartGameS.term", "docs.quests.conditionsStartGameS"),
                    new DocBullet("docs.quests.readOnlyQuestEach.term", "docs.quests.readOnlyQuestEach"),
                    new DocBullet("docs.quests.placesUnderStartedPut.term", "docs.quests.placesUnderStartedPut"),
                    new DocBullet("docs.quests.besidePlaceConversationShows.term", "docs.quests.besidePlaceConversationShows"),
                    new DocBullet("docs.quests.everyTaskListGame.term", "docs.quests.everyTaskListGame"),
                    new DocBullet("docs.quests.addingTakingOutTasks.term", "docs.quests.addingTakingOutTasks"),
                    new DocBullet("docs.quests.loadingSaveHasData.term", "docs.quests.loadingSaveHasData")),
                new DocSection("docs.quests.heading.worthKnowing",
                    new DocBullet("docs.quests.questNeedsNothingOutside"),
                    new DocBullet("docs.quests.gameOnlyFinishesTask"),
                    new DocBullet("docs.quests.finishingQuestGivesPlayer"),
                    new DocBullet("docs.quests.playersProgressSavedUnder")))),

        new DocPart("docs.part.conditionsActions",

            new DocTopic("docs.conditions.title",
                "docs.conditions.summary",
                new DocSection("docs.conditions.heading.variables",
                    new DocBullet("docs.conditions.compareVariableAgainstValue.term", "docs.conditions.compareVariableAgainstValue"),
                    new DocBullet("docs.conditions.passesWhenTextVariable.term", "docs.conditions.passesWhenTextVariable")),
                new DocSection("docs.conditions.heading.lists",
                    new DocBullet("docs.conditions.passesWhenListHolds.term", "docs.conditions.passesWhenListHolds"),
                    new DocBullet("docs.conditions.compareManyEntriesList.term", "docs.conditions.compareManyEntriesList")),
                new DocSection("docs.conditions.heading.whereThings",
                    new DocBullet("docs.conditions.passesWhileParticularPlace.term", "docs.conditions.passesWhileParticularPlace"),
                    new DocBullet("docs.conditions.passesWhileParticularObject.term", "docs.conditions.passesWhileParticularObject")),
                new DocSection("docs.conditions.heading.keyboardMouse",
                    new DocBullet("docs.conditions.passesKeyMouseButton.term", "docs.conditions.passesKeyMouseButton"),
                    new DocBullet("docs.conditions.momentsTrueOncePer.term", "docs.conditions.momentsTrueOncePer"),
                    new DocBullet("docs.conditions.statesTrueLongKey.term", "docs.conditions.statesTrueLongKey"),
                    new DocBullet("docs.conditions.gameReadsKeysPOSITION.term", "docs.conditions.gameReadsKeysPOSITION"),
                    new DocBullet("docs.conditions.gameMouseButtonJust.term", "docs.conditions.gameMouseButtonJust")),
                new DocSection("docs.conditions.heading.quests",
                    new DocBullet("docs.conditions.passesWhileOneQuests.term", "docs.conditions.passesWhileOneQuests"),
                    new DocBullet("docs.conditions.compareTaskSCount.term", "docs.conditions.compareTaskSCount")),
                new DocSection("docs.conditions.heading.chanceTime",
                    new DocBullet("docs.conditions.percentageRolledOncePer.term", "docs.conditions.percentageRolledOncePer"),
                    new DocBullet("docs.conditions.percentageRolledFreshEvery.term", "docs.conditions.percentageRolledFreshEvery"),
                    new DocBullet("docs.conditions.passesOnceIntervalHas.term", "docs.conditions.passesOnceIntervalHas")),
                new DocSection("docs.conditions.heading.others",
                    new DocBullet("docs.conditions.rainingSnowingEitherThem.term", "docs.conditions.rainingSnowingEitherThem"),
                    new DocBullet("docs.conditions.passesNoMatterUseful.term", "docs.conditions.passesNoMatterUseful")),
                new DocSection("docs.conditions.heading.whereEachOneOffered",
                    new DocBullet("docs.conditions.mostConditionsAvailableAnywhere"),
                    new DocBullet("docs.conditions.randomOfferedOnlyWhere"),
                    new DocBullet("docs.conditions.timerOfferedOnlyIntegration"),
                    new DocBullet("docs.conditions.inputkeyOfferedEverywhereBut")),
                new DocSection("docs.conditions.heading.theyCalledFile",
                    new DocBullet("docs.conditions.onlyNeededReadingModpack"),
                    new DocBullet("docs.conditions.oneVariableEntrySix"),
                    new DocBullet("docs.conditions.everythingElseWrittenUnder"),
                    new DocBullet("docs.conditions.gamevariableequalsGamevariablenumbergreaterthanGamevariablenumbergreaterorequalGamevariablenumberlessthan.term", "docs.conditions.gamevariableequalsGamevariablenumbergreaterthanGamevariablenumbergreaterorequalGamevariablenumberlessthan")),
                new DocSection("docs.conditions.heading.worthKnowing",
                    new DocBullet("docs.conditions.anyConditionCanNegated"),
                    new DocBullet("docs.conditions.seeConditionActionLists"))),

            new DocTopic("docs.actions.title",
                "docs.actions.summary",
                new DocSection("docs.actions.heading.variablesLists",
                    new DocBullet("docs.actions.writeVariableOperationChooses.term", "docs.actions.writeVariableOperationChooses"),
                    new DocBullet("docs.actions.appendValueList.term", "docs.actions.appendValueList"),
                    new DocBullet("docs.actions.takeFirstMatchingValue.term", "docs.actions.takeFirstMatchingValue"),
                    new DocBullet("docs.actions.emptyListCompletely.term", "docs.actions.emptyListCompletely")),
                new DocSection("docs.actions.heading.actors",
                    new DocBullet("docs.actions.liftCastSBusts.term", "docs.actions.liftCastSBusts"),
                    new DocBullet("docs.actions.playActorSFade.term", "docs.actions.playActorSFade")),
                new DocSection("docs.actions.heading.objectsScreen",
                    new DocBullet("docs.actions.switchObjectOffBust.term", "docs.actions.switchObjectOffBust"),
                    new DocBullet("docs.actions.swapArtworkWhateverTarget.term", "docs.actions.swapArtworkWhateverTarget"),
                    new DocBullet("docs.actions.reachComponentOtherActions.term", "docs.actions.reachComponentOtherActions"),
                    new DocBullet("docs.actions.fadePieceArtworkChosen.term", "docs.actions.fadePieceArtworkChosen"),
                    new DocBullet("docs.actions.slideObjectPositionOver.term", "docs.actions.slideObjectPositionOver"),
                    new DocBullet("docs.actions.startStopObjectRotating.term", "docs.actions.startStopObjectRotating")),
                new DocSection("docs.actions.heading.placesScenes",
                    new DocBullet("docs.actions.crossFadeOnePlace.term", "docs.actions.crossFadeOnePlace"),
                    new DocBullet("docs.actions.coverScreenWhileChanges.term", "docs.actions.coverScreenWhileChanges"),
                    new DocBullet("docs.actions.hideEveryScenePack.term", "docs.actions.hideEveryScenePack")),
                new DocSection("docs.actions.heading.signalsInterface",
                    new DocBullet("docs.actions.sendOneGameS.term", "docs.actions.sendOneGameS"),
                    new DocBullet("docs.actions.sameAfterWaitDialogue.term", "docs.actions.sameAfterWaitDialogue"),
                    new DocBullet("docs.actions.leaveInterfaceFadedWhen.term", "docs.actions.leaveInterfaceFadedWhen")),
                new DocSection("docs.actions.heading.sound",
                    new DocBullet("docs.actions.changeMusicPlaying.term", "docs.actions.changeMusicPlaying"),
                    new DocBullet("docs.actions.playSoundEffectStack.term", "docs.actions.playSoundEffectStack")),
                new DocSection("docs.actions.heading.timingChance",
                    new DocBullet("docs.actions.pauseBeforeNextAction.term", "docs.actions.pauseBeforeNextAction"),
                    new DocBullet("docs.actions.rollOnceDoExactly.term", "docs.actions.rollOnceDoExactly")),
                new DocSection("docs.actions.heading.quests",
                    new DocBullet("docs.actions.driveOneQuestsOne.term", "docs.actions.driveOneQuestsOne"),
                    new DocBullet("docs.actions.gameOnlyCompletesFails")),
                new DocSection("docs.actions.heading.world",
                    new DocBullet("docs.actions.changeTodaySWeather.term", "docs.actions.changeTodaySWeather")),
                new DocSection("docs.actions.heading.theyCalledFile",
                    new DocBullet("docs.actions.onlyNeededReadingModpack"),
                    new DocBullet("docs.actions.oneVariableEntryFour"),
                    new DocBullet("docs.actions.everythingElseWrittenUnder"),
                    new DocBullet("docs.actions.activatesceneSeparateActionShowing.term", "docs.actions.activatesceneSeparateActionShowing")),
                new DocSection("docs.actions.heading.worthKnowing",
                    new DocBullet("docs.actions.actionsRunOrderThey"),
                    new DocBullet("docs.actions.anythingTargetsObjectGives"))),

            new DocTopic("docs.targetPicker.title",
                "docs.targetPicker.summary",
                new DocSection("docs.targetPicker.heading.categories",
                    new DocBullet("docs.targetPicker.characterSBustCurrently.term", "docs.targetPicker.characterSBustCurrently"),
                    new DocBullet("docs.targetPicker.somethingPackAddedPlace.term", "docs.targetPicker.somethingPackAddedPlace"),
                    new DocBullet("docs.targetPicker.placeSOwnArtwork.term", "docs.targetPicker.placeSOwnArtwork"),
                    new DocBullet("docs.targetPicker.oneScenesName.term", "docs.targetPicker.oneScenesName"),
                    new DocBullet("docs.targetPicker.anythingElseNamedWhere.term", "docs.targetPicker.anythingElseNamedWhere")),
                new DocSection("docs.targetPicker.heading.restRow",
                    new DocBullet("docs.targetPicker.actOfferedWhateverCategory.term", "docs.targetPicker.actOfferedWhateverCategory"),
                    new DocBullet("docs.targetPicker.whichPlaceLookInside.term", "docs.targetPicker.whichPlaceLookInside"),
                    new DocBullet("docs.targetPicker.whichPlaceSTwo.term", "docs.targetPicker.whichPlaceSTwo")),
                new DocSection("docs.targetPicker.heading.worthKnowing",
                    new DocBullet("docs.targetPicker.notEveryActionOffers"),
                    new DocBullet("docs.targetPicker.gameobjectactiveConditionUsesSame"),
                    new DocBullet("docs.targetPicker.objectsStartSwitchedOff"),
                    new DocBullet("docs.targetPicker.targetResolvesNothingReported"),
                    new DocBullet("docs.targetPicker.conditionThereNoLog")))),

        new DocPart("docs.part.finishingPack",

            new DocTopic("docs.validating.title",
                "docs.validating.summary",
                new DocSection("",
                    new DocBullet("docs.validating.validateF5ChecksWhole"),
                    new DocBullet("docs.validating.errorsThingsWillNot"),
                    new DocBullet("docs.validating.warningsThingsWillRun"),
                    new DocBullet("docs.validating.referencesPlacesGameShips")),
                new DocSection("docs.validating.heading.worthKnowing",
                    new DocBullet("docs.validating.validateRunsAgainstScreen"),
                    new DocBullet("docs.validating.clearAnyDebugTracking"))),

            new DocTopic("docs.exportingInstalling.title",
                "docs.exportingInstalling.summary",
                new DocSection("",
                    new DocBullet("docs.exportingInstalling.savesThenBundlesPack.term", "docs.exportingInstalling.savesThenBundlesPack"),
                    new DocBullet("docs.exportingInstalling.alwaysAsksPlaceChoose.term", "docs.exportingInstalling.alwaysAsksPlaceChoose"),
                    new DocBullet("docs.exportingInstalling.putSmspackBepinexPlugins.term", "docs.exportingInstalling.putSmspackBepinexPlugins"),
                    new DocBullet("docs.exportingInstalling.eachSaveRecordsWhich.term", "docs.exportingInstalling.eachSaveRecordsWhich")),
                new DocSection("docs.exportingInstalling.heading.worthKnowing",
                    new DocBullet("docs.exportingInstalling.exportUnavailableUntilPack"),
                    new DocBullet("docs.exportingInstalling.seePacksSmspackEnds"))),

            new DocTopic("docs.translations.title",
                "docs.translations.summary",
                new DocSection("docs.translations.heading.editor",
                    new DocBullet("docs.translations.languageMenu.term", "docs.translations.languageMenu"),
                    new DocBullet("docs.translations.editMode.term", "docs.translations.editMode"),
                    new DocBullet("docs.translations.files.term", "docs.translations.files"),
                    new DocBullet("docs.translations.newOrUpdate.term", "docs.translations.newOrUpdate"),
                    new DocBullet("docs.translations.check.term", "docs.translations.check"),
                    new DocBullet("docs.translations.sharing.term", "docs.translations.sharing")),
                new DocSection("docs.translations.heading.packs",
                    new DocBullet("docs.translations.writtenIn.term", "docs.translations.writtenIn"),
                    new DocBullet("docs.translations.editingIn.term", "docs.translations.editingIn"),
                    new DocBullet("docs.translations.translatePack.term", "docs.translations.translatePack"),
                    new DocBullet("docs.translations.packFile.term", "docs.translations.packFile"),
                    new DocBullet("docs.translations.ai.term", "docs.translations.ai"),
                    new DocBullet("docs.translations.players.term", "docs.translations.players")),
                new DocSection("docs.translations.heading.game",
                    new DocBullet("docs.translations.setting"),
                    new DocBullet("docs.translations.fonts"),
                    new DocBullet("docs.translations.gameWords")),
                new DocSection("docs.translations.heading.worthKnowing",
                    new DocBullet("docs.translations.machine"),
                    new DocBullet("docs.translations.storedStays"),
                    new DocBullet("docs.translations.variables")))),
    };
}
