#!/usr/bin/env python3
"""
Regenerate `SMSModForge/Model/VanillaBusts.cs` from a fresh
CoreGameScene hierarchy dump. Use this when the target Starmaker Story
version changes and the bust list shifts.

Workflow:
    1. Re-dump the hierarchy. The SMSAndroids dev tooling produces a
       file like `CoreGameScene_Hierarchy_1.8E.txt`. Point this script at
       the new file with `--hierarchy`.
    2. The script extracts every direct child of `2_Bust_Manager` and
       writes the catalog to the .cs file at
       `--output` (defaults to the live one in this repo).
    3. Best-effort `Character` grouping is derived from the GO name —
       prefix before the first underscore, with a few hand-tuned
       overrides for special-cased names. Review/refine the result
       before committing.

Usage:
    python regen_vanilla_busts.py \
        --hierarchy ../../SMSAndroids/SMSAndroids/ReferenceClasses/CoreGameScene_Hierarchy_1.8E.txt \
        [--output ../SMSModForge/Model/VanillaBusts.cs]
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path
from typing import Iterator


# Hand-tuned display names: GO-name prefix → grouping label. The runtime
# only needs the GO names; this metadata is editor-side ergonomics.
CHARACTER_OVERRIDES: dict[str, str] = {
    "TomboyToni": "Toni",
    "XXX_Celeste": "Celeste",
    "doctorfrost": "Doctor Frost",
    "HimariMother": "Himari (Mother)",
    "HimariFather": "Himari (Father)",
    "Richwoman": "Rich Woman",
    "Richguy": "Rich Guy",
    "NurseNina": "NurseNina",
}


def find_section_bounds(lines: list[str]) -> tuple[int, int]:
    """Locate the `2_Bust_Manager` section. Returns (start_line_0idx, end_line_0idx).
    The end is the line BEFORE the next top-level `^- N_…` entry, exclusive."""
    start: int | None = None
    for i, line in enumerate(lines):
        if line.startswith("- 2_Bust_Manager "):
            start = i
            break
    if start is None:
        raise SystemExit("Could not find `- 2_Bust_Manager` in the hierarchy file")

    end = len(lines)
    for i in range(start + 1, len(lines)):
        if re.match(r"^- \d+_", lines[i]):
            end = i
            break
    return start, end


CHILD_RE = re.compile(r"^  - (\S+) \[self:")


def iter_busts(lines: list[str], start: int, end: int) -> Iterator[str]:
    for i in range(start + 1, end):
        m = CHILD_RE.match(lines[i])
        if m:
            yield m.group(1)


def derive_character(go_name: str) -> str:
    """Best-effort group label. Pack authors only see this in the picker."""
    for prefix, label in CHARACTER_OVERRIDES.items():
        if go_name.startswith(prefix):
            return label
    # Default: take the segment before the first underscore.
    base = go_name.split("_", 1)[0]
    # Strip a trailing "Bust" so e.g. `CharlotteBust` → `Charlotte`.
    if base.endswith("Bust") and len(base) > 4:
        base = base[: -len("Bust")]
    return base


def render(busts: list[tuple[str, str]]) -> str:
    header = '''using System.Collections.Generic;

namespace SMSModForge.Model;

/// <summary>
/// Catalog of vanilla bust GameObjects under <c>2_Bust_Manager</c> in
/// <c>CoreGameScene</c> in Starmaker Story (see header below for game
/// version). Used by the Actors tab so an actor's "default bust" can
/// point at an existing in-game character without the pack needing to
/// ship one of its own.
/// <para/>
/// Regenerated by <c>Tools/regen_vanilla_busts.py</c> from a fresh
/// hierarchy dump.
/// </summary>
public static class VanillaBusts
{
    public sealed record VanillaBust(string GoName, string Character);

    public static readonly IReadOnlyList<VanillaBust> All = new VanillaBust[]
    {
'''
    body_lines = []
    name_w = max(len(go) for go, _ in busts) + 2
    for go, char in busts:
        # Quote and pad so the file diffs cleanly when entries get added.
        go_q = f'"{go}"'
        char_q = f'"{char}"'
        body_lines.append(f"        new({go_q.ljust(name_w + 2)}, {char_q}),")
    footer = '''    };

    /// <summary>Lookup by GO name. Returns null if the name isn't in the catalog.</summary>
    public static VanillaBust? FindByGoName(string goName)
    {
        foreach (var b in All)
            if (b.GoName == goName) return b;
        return null;
    }
}
'''
    return header + "\n".join(body_lines) + "\n" + footer


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--hierarchy", required=True, type=Path,
                        help="Path to CoreGameScene_Hierarchy_<version>.txt")
    parser.add_argument("--output", type=Path,
                        default=Path(__file__).resolve().parent.parent / "SMSModForge" / "Model" / "VanillaBusts.cs",
                        help="Output .cs file (defaults to the repo's live catalog)")
    args = parser.parse_args()

    lines = args.hierarchy.read_text(encoding="utf-8").splitlines()
    start, end = find_section_bounds(lines)
    busts = [(go, derive_character(go)) for go in iter_busts(lines, start, end)]
    print(f"Extracted {len(busts)} busts from {args.hierarchy}")
    args.output.write_text(render(busts), encoding="utf-8")
    print(f"Wrote {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
