#!/usr/bin/env python3
"""Rebuild `Shared/VanillaBustExpressions.cs` from the bust art extraction.

WHERE IT COMES FROM
    Every extracted bust folder carries a `_contents.txt` recording the
    GameObject each sprite was taken from:

        ExpressionAngry.PNG  <-  MBase1/Expressions/Angry  |  X_0004_Angry  |  256x256

    So the game's own expressions are already written down; nothing has to be
    guessed at or typed. That file documents the extraction and is deliberately
    not shipped, which is exactly why this exists: the fact has to reach the
    editor and the runtime as compiled data instead.

WHAT IT FINDS
    Across 318 extracted busts the answer is completely uniform: 232 of them
    have Angry, Flirty, Happy and Sad -- all four, always -- and 86 have none
    at all. Not one bust has three, or a fifth. So this is a membership
    question rather than a per-bust list, and the generated file says so.

    If a future extraction breaks that uniformity this script refuses to write
    rather than quietly flattening it, because "all four or none" is an
    assumption the editor's UI is built on.

WHAT IS DELIBERATELY LEFT OUT
    Busts absent from the shipped catalog. Some exist in the game with no
    content showing them -- unreleased work -- and they are excluded from
    Shared/VanillaCastData.cs on purpose. Naming them here would put them back
    in the repository through a side door.

    `neutral`, which the vanilla dialogues reference 700 times, is not an
    Expressions child and never was: it means no expression active, which is
    the bust's own face. The editor offers it as the absence of a choice.

Usage:
    python Tools/regen_vanilla_expressions.py
    python Tools/regen_vanilla_expressions.py --check    # report, write nothing
"""

import argparse
import io
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, ".."))
ART = os.path.join(REPO, "SMSModForge", "Resources", "VanillaBustArt")
CATALOG = os.path.join(REPO, "Shared", "VanillaCastData.cs")
OUT = os.path.join(REPO, "Shared", "VanillaBustExpressions.cs")

EXPECTED = ("Angry", "Flirty", "Happy", "Sad")


def catalogued():
    """The bust names the tool actually offers. See the note above."""
    src = io.open(CATALOG, encoding="utf-8-sig").read()
    names = set(re.findall(r'new VanillaBust\("([^"]+)"', src))
    if not names:
        sys.exit("could not read any bust names from %s -- refusing to write a "
                 "dataset with no catalog to check it against" % CATALOG)
    return names


def expressions_of(contents_path):
    """The Expressions children one bust declares, from its extraction record."""
    found = set()
    for line in io.open(contents_path, encoding="utf-8"):
        m = re.search(r"<-\s+([^|]+?)\s+\|", line)
        if m and "/Expressions/" in m.group(1):
            found.add(m.group(1).strip().split("/Expressions/")[-1])
    return tuple(sorted(found))


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true",
                    help="report what would be written, write nothing")
    args = ap.parse_args()

    allowed = catalogued()
    expressive, bare, skipped = [], 0, 0

    for name in sorted(os.listdir(ART)):
        record = os.path.join(ART, name, "_contents.txt")
        if not os.path.isfile(record):
            continue
        if name not in allowed:
            skipped += 1
            continue

        found = expressions_of(record)
        if not found:
            bare += 1
        elif found == EXPECTED:
            expressive.append(name)
        else:
            sys.exit("%s has %s, not the uniform %s. The editor assumes all "
                     "four or none; decide what that means before regenerating."
                     % (name, ", ".join(found) or "nothing", ", ".join(EXPECTED)))

    print("%d catalogued busts with expressions, %d without, %d not in the catalog"
          % (len(expressive), bare, skipped))

    body = "\n".join('            "%s",' % b for b in expressive)
    text = TEMPLATE % {"count": len(expressive), "bare": bare, "busts": body}

    if args.check:
        print("(--check: nothing was written)")
        return
    io.open(OUT, "w", encoding="utf-8-sig", newline="\r\n").write(text)
    print("wrote %s" % OUT)


TEMPLATE = '''namespace SMSModForge.Shared
{
    /// <summary>
    /// Which of the game's busts can pull a face, and which faces those are.
    /// <para/>
    /// GENERATED by Tools/regen_vanilla_expressions.py from the bust art
    /// extraction, where every sprite records the GameObject it came from.
    /// Do not edit by hand.
    /// <para/>
    /// Compiled into both projects, for the usual reason: the editor offers an
    /// author the expressions a character actually has, and the runtime has to
    /// find the ones an author used. Two copies would disagree the first time
    /// the game added a face.
    /// <para/>
    /// The shape is a membership test rather than a list per bust because the
    /// game is completely uniform about it: %(count)d busts have all four of
    /// these and %(bare)d have none, and not one has some other combination.
    /// The generator refuses to write if that ever stops being true.
    /// </summary>
    public static class VanillaBustExpressions
    {
        /// <summary>
        /// The four faces, as they are named under
        /// <c>&lt;bust&gt;/MBase1/Expressions/</c>.
        /// <para/>
        /// <c>neutral</c> is not among them and never was, though the game's
        /// own dialogues ask for it constantly: it means no expression active,
        /// which is the bust's ordinary face rather than a child to switch on.
        /// </summary>
        public static readonly string[] Standard = { "Angry", "Flirty", "Happy", "Sad" };

        /// <summary>Whether this bust has the four. Names are compared exactly,
        /// the way the scene spells them.</summary>
        public static bool Has(string bustGoName)
        {
            return !string.IsNullOrEmpty(bustGoName) && Expressive.Contains(bustGoName);
        }

        /// <summary>The expressions this bust offers: the four, or none.</summary>
        public static string[] For(string bustGoName)
        {
            return Has(bustGoName) ? Standard : Empty;
        }

        private static readonly string[] Empty = new string[0];

        private static readonly System.Collections.Generic.HashSet<string> Expressive =
            new System.Collections.Generic.HashSet<string>(System.StringComparer.Ordinal)
        {
%(busts)s
        };
    }
}
'''


if __name__ == "__main__":
    main()
